# Generated by Django 5.2.6 on 2026-01-09 13:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Official company name",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        help_text="Primary company email address",
                        max_length=254,
                        verbose_name="Company Email",
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(
                        help_text="Company phone number with country code",
                        max_length=20,
                        verbose_name="Company Phone",
                    ),
                ),
                (
                    "company_addresses",
                    models.TextField(
                        help_text="Company branch addresses (one per line or comma-separated)",
                        verbose_name="Company Addresses",
                    ),
                ),
                (
                    "company_logo",
                    models.URLField(
                        blank=True,
                        help_text="URL to the company logo (upload via /upload-file endpoint)",
                        max_length=500,
                        null=True,
                        verbose_name="Company Logo",
                    ),
                ),
                (
                    "rc_number",
                    models.CharField(
                        help_text="Company registration number",
                        max_length=50,
                        verbose_name="RC Number",
                    ),
                ),
                (
                    "primary_color_code",
                    models.CharField(
                        default="#FE0000",
                        help_text="Hex color code (e.g., #FE0000)",
                        max_length=7,
                        verbose_name="Primary Color Code",
                    ),
                ),
                (
                    "secondary_color_code",
                    models.CharField(
                        default="#3E4094",
                        help_text="Hex color code (e.g., #3E4094)",
                        max_length=7,
                        verbose_name="Secondary Color Code",
                    ),
                ),
                (
                    "company_slogan",
                    models.CharField(
                        blank=True,
                        help_text="Company tagline or slogan",
                        max_length=255,
                        verbose_name="Company Slogan",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("NGN", "NGN Naira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="NGN",
                        max_length=3,
                        verbose_name="Default Currency",
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("en-GB", "English UK"),
                            ("en-US", "English US"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                        ],
                        default="en-GB",
                        max_length=10,
                        verbose_name="Language Preference",
                    ),
                ),
                (
                    "business_rules",
                    models.TextField(
                        blank=True,
                        help_text="Company business rules and policies",
                        verbose_name="Business Rules",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Country Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 code (e.g., USA, GBR, NGA)",
                        max_length=3,
                        unique=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("marketing", "Marketing"),
                            ("finance", "Finance"),
                            ("it", "Information Technology"),
                            ("hr", "Human Resources"),
                            ("legal", "Legal"),
                        ],
                        help_text="Department name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Department description"),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("intern", "Intern"),
                            ("junior", "Junior"),
                            ("mid_level", "Mid Level"),
                            ("senior", "Senior"),
                            ("head", "Head of Department"),
                            ("manager", "Manager"),
                            ("ceo", "Chief Executive Officer"),
                            ("cto", "Chief Technology Officer"),
                            ("cfo", "Chief Financial Officer"),
                            ("clo", "Chief Legal Officer"),
                            ("chro", "Chief Human Resources Officer"),
                            ("cmo", "Chief Marketing Officer"),
                        ],
                        help_text="Employee level",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Level",
                "verbose_name_plural": "Employee Levels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User email address (must be unique)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True,
                        help_text="Employee profile picture",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Employee first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Employee last name", max_length=100),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        help_text="Employee gender",
                        max_length=20,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        default="single",
                        help_text="Employee marital status",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(default="", help_text="Employee address")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Employee mobile number",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Employee date of birth", null=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user's email has been verified",
                    ),
                ),
                ("fingerprint_template", models.BinaryField(blank=True, null=True)),
                ("face_template", models.BinaryField(blank=True, null=True)),
                ("biometric_enabled", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user account was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When user account was last updated"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        help_text="Name of the branch",
                        max_length=255,
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "branch_id",
                    models.CharField(
                        help_text="Unique identifier for the branch",
                        max_length=50,
                        unique=True,
                        verbose_name="Branch ID",
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        blank=True,
                        help_text="Local Government Area",
                        max_length=100,
                        verbose_name="L.G.A",
                    ),
                ),
                (
                    "office_address",
                    models.TextField(
                        help_text="Complete office address",
                        verbose_name="Office Address",
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("under_maintenance", "Under Maintenance"),
                            ("temporarily_closed", "Temporarily Closed"),
                            ("permanently_closed", "Permanently Closed"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Operational Status",
                    ),
                ),
                (
                    "branch_role",
                    models.CharField(
                        choices=[
                            ("branch", "Branch"),
                            ("state_headquarters", "State Headquarters"),
                            (
                                "interstate_regional_headquarters",
                                "Inter State Regional Headquarters",
                            ),
                            ("national_headquarters", "National Headquarters"),
                        ],
                        default="branch_office",
                        max_length=50,
                        verbose_name="Branch Role",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Branch contact email",
                        max_length=254,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="Branch contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "branch_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional branch document (doc, docx, pdf)",
                        null=True,
                        upload_to="branches/files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["doc", "docx", "pdf"]
                            )
                        ],
                        verbose_name="Branch File",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the branch",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_branches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="user.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee ID", max_length=50, unique=True
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-Time"),
                            ("part-time", "Part-Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("freelance", "Freelance"),
                        ],
                        default="full-time",
                        help_text="Type of employment",
                        max_length=20,
                    ),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True,
                        help_text="Employee profile picture",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Employment start date", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the employee is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch where employee works",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="user.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department where employee works",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="user.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="Employee job designation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="user.employeelevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.OneToOneField(
                blank=True,
                help_text="Head of this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_department",
                to="user.employee",
            ),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User email address (must be unique)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True,
                        help_text="Employee profile picture",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Employee first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Employee last name", max_length=100),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        help_text="Employee gender",
                        max_length=20,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        default="single",
                        help_text="Employee marital status",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(default="", help_text="Employee address")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Employee mobile number",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("referral", "Referral"),
                            ("website", "Website"),
                            ("social_media", "Social Media"),
                            ("advertisement", "Advertisement"),
                            ("direct_contact", "Direct Contact"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="How the lead was acquired",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Lead"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("negotiating", "Negotiating"),
                            ("converted", "Converted to Client"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        help_text="Current status of the lead",
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Lead's company (if applicable)",
                        max_length=200,
                    ),
                ),
                (
                    "interested_services",
                    models.TextField(
                        help_text="Description of services/properties interested in"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the lead"
                    ),
                ),
                (
                    "last_contacted",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the lead was last contacted",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales/Account manager assigned to this lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("phone_verification", "Phone Verification"),
                        ],
                        default="password_reset",
                        help_text="Purpose/intent of this OTP code",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The actual OTP code", max_length=255, unique=True
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("numeric", "6-Digit Numeric Code"),
                            ("alphanumeric", "Alphanumeric Code"),
                        ],
                        default="numeric",
                        help_text="Type of code generated",
                        max_length=20,
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this code has been used"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the code was used", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this code expires"),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of failed validation attempts"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of validation attempts allowed",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which code was requested",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent from request"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (email being verified, phone number, etc.)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this OTP is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Code",
                "verbose_name_plural": "OTP Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="State Name")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="State/Province code",
                        max_length=10,
                        verbose_name="State Code",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="user.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="user.state",
                verbose_name="State",
            ),
        ),
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="The JWT token that has been blacklisted",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "blacklisted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the token was blacklisted"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        default="logout",
                        help_text="Reason for blacklisting (logout, security, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token naturally expires (for cleanup)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owned this token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
                "ordering": ["-blacklisted_at"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("name", models.CharField(help_text="Unit/Team name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Unit description"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Parent department",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="user.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        help_text="Type of event that occurred", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the event"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the action was performed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="user_auditl_created_566317_idx"
                    ),
                    models.Index(fields=["event"], name="user_auditl_event_b8df1c_idx"),
                    models.Index(
                        fields=["user"], name="user_auditl_user_id_b2a30d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Full name of the user", max_length=255),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Email address of the user",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Phone number", max_length=20),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("real_estate_license", "Real Estate License"),
                            ("broker_license", "Broker License"),
                            ("property_manager_license", "Property Manager License"),
                            (
                                "fair_housing_certification",
                                "Fair Housing Certification",
                            ),
                            (
                                "continuing_education",
                                "Continuing Education Certificate",
                            ),
                        ],
                        help_text="Type of compliance",
                        max_length=100,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number for the compliance record",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "date_of_issue",
                    models.DateField(help_text="Date when compliance was issued"),
                ),
                (
                    "expiry_date",
                    models.DateField(help_text="Expiry date of the compliance"),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="Authority that issued the compliance", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        help_text="Current status of the compliance",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the compliance", null=True
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Contact person for this compliance",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email",
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost associated with compliance",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Priority level",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("documents", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department where employee works",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance",
                        to="user.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Record",
                "verbose_name_plural": "Compliance Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="user_compli_status_c7c28c_idx"
                    ),
                    models.Index(
                        fields=["date_of_issue"], name="user_compli_date_of_005f6a_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="user_compli_expiry__371ca6_idx"
                    ),
                    models.Index(
                        fields=["department"], name="user_compli_departm_bd395c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_id"], name="user_employ_employe_7a79b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="user_lead_email_97795c_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "assigned_to"], name="user_lead_status_716e12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["-created_at"], name="user_lead_created_22b235_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "intent"], name="user_otpcod_user_id_c9de2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(fields=["code"], name="user_otpcod_code_935a45_idx"),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["expires_at"], name="user_otpcod_expires_82eecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["is_used"], name="user_otpcod_is_used_c0cfc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "is_used", "intent"],
                name="user_otpcod_user_id_7eaa7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["branch_id"], name="user_branch_branch__6e132f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["country", "state"], name="user_branch_country_841746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["operational_status"], name="user_branch_operati_03845a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["token"], name="user_tokenb_token_a3d0a8_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(
                fields=["blacklisted_at"], name="user_tokenb_blackli_3e7be6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("name", "department")},
        ),
    ]
