# Generated by Django 5.2.6 on 2026-01-12 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("clock_in", "Clock In"), ("clock_out", "Clock Out")],
                        help_text="Type of attendance record",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the clock-in/out occurred",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("biometric_fingerprint", "Biometric - Fingerprint"),
                            ("biometric_face", "Biometric - Face"),
                            ("manual", "Manual Entry"),
                            ("qr_code", "QR Code"),
                        ],
                        default="manual",
                        help_text="Method used to verify identity",
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location where clock-in/out occurred (GPS coordinates or address)",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments"
                    ),
                ),
                (
                    "match_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence level of biometric match (0-100%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee who clocked in/out",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-timestamp"],
                        name="user_attend_employe_1900cd_idx",
                    ),
                    models.Index(
                        fields=["attendance_type", "-timestamp"],
                        name="user_attend_attenda_0f6a6d_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="user_attend_timesta_aa7019_idx"
                    ),
                ],
            },
        ),
    ]
