# Generated by Django 5.2.6 on 2026-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="location",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("biometric_fingerprint", "Biometric - Fingerprint"),
                    ("biometric_face", "Biometric - Face"),
                    ("manual", "Manual Entry"),
                ],
                default="manual",
                help_text="Method used to verify identity",
                max_length=30,
            ),
        ),
    ]
