# Generated by Django 5.2.6 on 2026-01-12 15:00

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_attendance_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CLientInventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the inventory item",
                        max_length=200,
                        verbose_name="Item Name",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity available",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("bags", "Bags"), ("uni", "Units"), ("tons", "Tons")],
                        help_text="Unit of measurement",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value in Naira (₦)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total Value",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("low", "Low"),
                            ("percentage", "Percentage"),
                        ],
                        help_text="Current status of the item",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_value",
                    models.CharField(
                        blank=True,
                        help_text="Additional status information (e.g., percentage)",
                        max_length=50,
                        null=True,
                        verbose_name="Status Value",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["item_name"],
                "indexes": [
                    models.Index(
                        fields=["item_name"], name="user_client_item_na_46d640_idx"
                    ),
                    models.Index(
                        fields=["status"], name="user_client_status_71aed2_idx"
                    ),
                ],
            },
        ),
    ]
