# Generated by Django 5.2.6 on 2026-01-19 09:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_clientinventoryitem_status_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinventoryitem",
            name="quantity_used",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quantity available",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Quantity",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-Time"),
                    ("part-time", "Part-Time"),
                    ("contract", "Contract"),
                    ("intern", "Intern"),
                    ("freelance", "Freelance"),
                    ("associate", "Associate"),
                ],
                default="full-time",
                help_text="Type of employment",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_name",
                    models.CharField(
                        help_text="Full name of the audit (e.g., 'ISO 9001-2015 Quality Management')",
                        max_length=500,
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("external", "External"),
                            ("regulatory", "Regulatory"),
                            ("internal", "Internal"),
                            ("customer", "Customer"),
                            ("financial", "Financial"),
                            ("operational", "Operational"),
                            ("compliance", "Compliance"),
                        ],
                        help_text="Type of audit",
                        max_length=50,
                    ),
                ),
                (
                    "auditor_name",
                    models.CharField(
                        help_text="Name of the auditor (e.g., 'Mrs. Funmi Adebayo')",
                        max_length=200,
                    ),
                ),
                (
                    "auditor_title",
                    models.CharField(
                        blank=True,
                        help_text="Professional title of auditor (e.g., 'Engr. Dr.', 'Mrs.')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("scheduled", "Scheduled"),
                            ("draft", "Draft"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        help_text="Current status of the audit",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Audit score as a percentage (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("audit_date", models.DateField(help_text="Date of the audit")),
                (
                    "audit_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique audit reference number",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the audit scope"
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Key findings from the audit"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for improvement"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Date when audit started", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Date when audit was completed", null=True
                    ),
                ),
                (
                    "auditor_organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization the auditor represents",
                        max_length=300,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department being audited", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit",
                "verbose_name_plural": "Audits",
                "ordering": ["-audit_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="user_audit_status_a4813a_idx"
                    ),
                    models.Index(
                        fields=["audit_type"], name="user_audit_audit_t_60e813_idx"
                    ),
                    models.Index(
                        fields=["audit_date"], name="user_audit_audit_d_938602_idx"
                    ),
                    models.Index(fields=["score"], name="user_audit_score_36dc86_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_name",
                    models.CharField(
                        help_text="Full name of the case (e.g., 'Bomach Engineering vs. Delta Construction')",
                        max_length=500,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("contract_dispute", "Contract Dispute"),
                            ("employment", "Employment"),
                            ("regulatory", "Regulatory"),
                            ("civil", "Civil"),
                            ("criminal", "Criminal"),
                            ("corporate", "Corporate"),
                            ("intellectual_property", "Intellectual Property"),
                        ],
                        help_text="Type of legal case",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("settled", "Settled"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                            ("dismissed", "Dismissed"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="open",
                        help_text="Current status of the case",
                        max_length=20,
                    ),
                ),
                (
                    "exposure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Financial exposure amount in Naira",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "next_hearing",
                    models.DateField(
                        blank=True,
                        help_text="Date of the next scheduled hearing",
                        null=True,
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        help_text="Official case number from court/regulatory body",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the case"
                    ),
                ),
                (
                    "date_filed",
                    models.DateField(
                        blank=True, help_text="Date when the case was filed", null=True
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        blank=True,
                        help_text="Date when the case was closed/settled",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Case",
                "verbose_name_plural": "Legal Cases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="user_legalc_status_30985d_idx"
                    ),
                    models.Index(
                        fields=["case_type"], name="user_legalc_case_ty_eb9f00_idx"
                    ),
                    models.Index(
                        fields=["next_hearing"], name="user_legalc_next_he_cfc785_idx"
                    ),
                ],
            },
        ),
    ]
