# Generated by Django 5.2.6 on 2026-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_clientinventoryitem_quantity_used_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="user_auditl_created_566317_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="user_auditl_event_b8df1c_idx",
        ),
        migrations.RenameField(
            model_name="auditlog",
            old_name="description",
            new_name="activity",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="event",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="audit_status",
            field=models.CharField(
                choices=[("warning", "Warning"), ("info", "Info")],
                default="info",
                help_text="Audit status",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="audit_type",
            field=models.CharField(
                choices=[("login", "Login"), ("update_profile", "Update Profile")],
                default="login",
                help_text="Audit type",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["audit_type"], name="user_auditl_audit_t_6bc1ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["audit_status"], name="user_auditl_audit_s_278eac_idx"
            ),
        ),
    ]
