# Generated by Django 5.2.6 on 2026-02-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_auditlog_user_auditl_created_566317_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Client's current account balance",
                max_digits=15,
            ),
        ),
    ]
