# Generated by Django 5.2.6 on 2026-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_transaction_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="head_of_department",
        ),
    ]
