# Generated by Django 5.2.6 on 2026-02-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_department_head_of_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department_unit",
            field=models.ForeignKey(
                help_text="Department unit where employee works",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="user.unit",
            ),
        ),
    ]
