# Generated by Django 5.2.6 on 2026-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_employee_department_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True, default="", help_text="Employee address", null=True
            ),
        ),
    ]
