# Generated by Django 5.2.6 on 2026-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="address",
            field=models.TextField(blank=True, help_text="Employee address", null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Lead's company (if applicable)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                help_text="Employee gender",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                help_text="Employee marital status",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about the lead", null=True
            ),
        ),
    ]
