# Generated by Django 5.2.6 on 2026-02-13 09:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_lead_address_alter_lead_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="allowances",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Allowances breakdown as key-value pairs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gross_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-Time"),
                    ("part-time", "Part-Time"),
                    ("intern", "Intern"),
                    ("contract", "Contract"),
                    ("freelance", "Freelance"),
                    ("surveyor-associate", "Surveyor Associate"),
                    ("lawyer-associate", "Lawyer Associate"),
                    ("architect-associate", "Architect Associate"),
                    ("engineer-associate", "Engineer Associate"),
                ],
                default="full-time",
                help_text="Type of employment",
                max_length=20,
            ),
        ),
    ]
