# Generated by Django 5.2.6 on 2026-02-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_employee_allowances_employee_gross_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch where employee works",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="user.branch",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department where employee works",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="user.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Department unit where employee works",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="user.unit",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee job designation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="user.employeelevel",
            ),
        ),
    ]
