# Generated by Django 5.2.6 on 2026-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_employee_branch_alter_employee_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="Employee first name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, help_text="Employee last name", max_length=100
            ),
        ),
    ]
