# Generated by Django 5.2.6 on 2026-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("NGN", "NGN - Nigerian Naira"),
                    ("GHS", "GHS - Ghanaian Cedi"),
                    ("KES", "KES - Kenyan Shilling"),
                    ("ZAR", "ZAR - South African Rand"),
                    ("EGP", "EGP - Egyptian Pound"),
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound Sterling"),
                    ("CAD", "CAD - Canadian Dollar"),
                    ("AUD", "AUD - Australian Dollar"),
                    ("JPY", "JPY - Japanese Yen"),
                    ("CHF", "CHF - Swiss Franc"),
                    ("CNY", "CNY - Chinese Yuan"),
                    ("INR", "INR - Indian Rupee"),
                    ("AED", "AED - UAE Dirham"),
                    ("SAR", "SAR - Saudi Riyal"),
                    ("SGD", "SGD - Singapore Dollar"),
                ],
                default="NGN",
                max_length=3,
                verbose_name="Default Currency",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="language_preference",
            field=models.CharField(
                choices=[
                    ("en-GB", "English UK"),
                    ("en-US", "English US"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                ],
                default="en-GB",
                max_length=10,
                verbose_name="Language Preference",
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("NGN", "NGN - Nigerian Naira"),
                    ("GHS", "GHS - Ghanaian Cedi"),
                    ("KES", "KES - Kenyan Shilling"),
                    ("ZAR", "ZAR - South African Rand"),
                    ("EGP", "EGP - Egyptian Pound"),
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound Sterling"),
                    ("CAD", "CAD - Canadian Dollar"),
                    ("AUD", "AUD - Australian Dollar"),
                    ("JPY", "JPY - Japanese Yen"),
                    ("CHF", "CHF - Swiss Franc"),
                    ("CNY", "CNY - Chinese Yuan"),
                    ("INR", "INR - Indian Rupee"),
                    ("AED", "AED - UAE Dirham"),
                    ("SAR", "SAR - Saudi Riyal"),
                    ("SGD", "SGD - Singapore Dollar"),
                ],
                default="NGN",
                max_length=3,
                verbose_name="Default Currency",
            ),
        ),
    ]
