# Generated by Django 5.2.6 on 2026-02-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_country_default_currency_country_language_preference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchBusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Opening Time"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Closing Time"
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="Is Open")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="user.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Business Hours",
                "verbose_name_plural": "Branch Business Hours",
                "ordering": ["day_of_week"],
                "unique_together": {("branch", "day_of_week")},
            },
        ),
    ]
