# Generated by Django 5.2.6 on 2026-02-23 10:17

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_branch_business_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeelevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("intern", "Intern"),
                    ("junior", "Junior"),
                    ("mid_level", "Mid Level"),
                    ("senior", "Senior"),
                    ("head", "Head of Department"),
                    ("manager", "Manager"),
                    ("ceo", "Chief Executive Officer"),
                    ("cto", "Chief Technology Officer"),
                    ("cfo", "Chief Financial Officer"),
                    ("clo", "Chief Legal Officer"),
                    ("chro", "Chief Human Resources Officer"),
                    ("cmo", "Chief Marketing Officer"),
                    ("board_member", "Board Member"),
                ],
                help_text="Employee level",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "shareholder_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Shareholder ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("chairman", "Chairman"),
                            ("vice_chairman", "Vice Chairman"),
                            ("executive_director", "Executive Director"),
                            ("non_executive_director", "Non-Executive Director"),
                            ("board_member", "Board Member"),
                        ],
                        default="board_member",
                        max_length=50,
                        verbose_name="Board Title",
                    ),
                ),
                (
                    "share_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage ownership in the company (0.00 - 100.00)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Share Percentage",
                    ),
                ),
                (
                    "share_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of shares held",
                        null=True,
                        verbose_name="Share Count",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shareholder_profile",
                        to="user.employee",
                        verbose_name="Employee Profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholder_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shareholder",
                "verbose_name_plural": "Shareholders",
                "ordering": ["-share_percentage", "-created_at"],
            },
        ),
    ]
