# Generated by Django 5.2.6 on 2026-02-23 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_shareholder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "announcement_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Announcement ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("urgent", "Urgent"),
                            ("event", "Event"),
                            ("policy", "Policy Update"),
                            ("reminder", "Reminder"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule a future publish time. Leave blank to publish immediately.",
                        null=True,
                        verbose_name="Publish At",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiry date/time after which the announcement is no longer shown.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to target all branches",
                        related_name="announcements",
                        to="user.branch",
                        verbose_name="Target Branches",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to target all departments",
                        related_name="announcements",
                        to="user.department",
                        verbose_name="Target Departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["announcement_type"],
                        name="user_announ_announc_e296a3_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="user_announ_priorit_063e06_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="user_announ_is_acti_f54aaa_idx"
                    ),
                ],
            },
        ),
    ]
