# Generated by Django 5.2.6 on 2026-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareholder",
            name="is_board_member",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this shareholder sits on the board of directors",
                verbose_name="Is Board Member",
            ),
        ),
        migrations.AlterField(
            model_name="shareholder",
            name="title",
            field=models.CharField(
                choices=[
                    ("founder", "Founder"),
                    ("co_founder", "Co Founder"),
                    ("chairman", "Chairman"),
                    ("vice_chairman", "Vice Chairman"),
                    ("executive_director", "Executive Director"),
                    ("non_executive_director", "Non-Executive Director"),
                    ("board_member", "Board Member"),
                ],
                default="board_member",
                max_length=50,
                verbose_name="Board Title",
            ),
        ),
    ]
