# Generated by Django 5.2.6 on 2026-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_shareholder_is_board_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the request", null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional context about the event (e.g. affected record name/id)",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                help_text="Audit status",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("forgot_password", "Forgot Password"),
                    ("reset_password", "Reset Password"),
                    ("add_employee", "Add Employee"),
                    ("update_employee", "Update Employee"),
                    ("update_profile", "Update Profile"),
                    ("add_client", "Add Client"),
                    ("add_lead", "Add Lead"),
                ],
                help_text="Audit type",
                max_length=100,
            ),
        ),
    ]
