# Generated by Django 5.2.6 on 2026-02-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_audit_log_security_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "policy_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Policy ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("work_ethics", "Work Ethics"),
                            ("hiring", "Hiring & Recruitment"),
                            ("leave", "Leave & Time Off"),
                            ("code_of_conduct", "Code of Conduct"),
                            ("data_privacy", "Data Privacy & Security"),
                            ("health_and_safety", "Health & Safety"),
                            ("compensation", "Compensation & Benefits"),
                            ("performance", "Performance Management"),
                            ("disciplinary", "Disciplinary Procedures"),
                            ("remote_work", "Remote Work"),
                            ("it_usage", "IT & Technology Usage"),
                            ("anti_harassment", "Anti-Harassment & Discrimination"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                ("content", models.TextField(verbose_name="Policy Content")),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="e.g. 1.0, 2.1",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("under_review", "Under Review"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date the policy comes into effect",
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Review Date"
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the full policy document (uploaded separately)",
                        max_length=500,
                        verbose_name="Attachment URL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all departments",
                        related_name="policies",
                        to="user.department",
                        verbose_name="Applicable Departments",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "ordering": ["category", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="user_policy_categor_fc0a1c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="user_policy_status_6f6236_idx"
                    ),
                    models.Index(
                        fields=["effective_date"], name="user_policy_effecti_9a3b59_idx"
                    ),
                ],
            },
        ),
    ]
