# Generated by Django 5.2.6 on 2026-02-23 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Meeting ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "agenda",
                    models.TextField(
                        help_text="Meeting agenda and discussion points",
                        verbose_name="Agenda",
                    ),
                ),
                ("meeting_date", models.DateField(verbose_name="Meeting Date")),
                ("meeting_time", models.TimeField(verbose_name="Meeting Time")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Expected duration of the meeting in minutes",
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="physical",
                        max_length=20,
                        verbose_name="Location Type",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Room name, address, or virtual meeting link",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or minutes after the meeting",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attendees",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-meeting_date", "-meeting_time"],
                "indexes": [
                    models.Index(
                        fields=["meeting_date"], name="user_meetin_meeting_d752e4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="user_meetin_status_e7bd0a_idx"
                    ),
                ],
            },
        ),
    ]
