# Generated by Django 5.2.6 on 2026-02-23 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "resolution_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Resolution ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("operational", "Operational"),
                            ("strategic", "Strategic"),
                            ("legal", "Legal & Compliance"),
                            ("hr", "Human Resources"),
                            ("investment", "Investment"),
                            ("governance", "Governance"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolution_date",
                    models.DateField(
                        help_text="Date the resolution was created or passed",
                        verbose_name="Resolution Date",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to the full resolution document",
                        max_length=500,
                        verbose_name="Attachment URL",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board Resolution",
                "verbose_name_plural": "Board Resolutions",
                "ordering": ["-resolution_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="user_boardr_status_db8c2c_idx"
                    ),
                    models.Index(
                        fields=["resolution_type"],
                        name="user_boardr_resolut_2fa1b2_idx",
                    ),
                    models.Index(
                        fields=["resolution_date"],
                        name="user_boardr_resolut_cc9a15_idx",
                    ),
                ],
            },
        ),
    ]
