# Generated by Django 5.2.6 on 2026-02-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_board_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardresolution",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
