# Generated by Django 5.2.6 on 2026-02-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0026_alter_boardresolution_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Flow Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("leave_request", "Leave Request"),
                            ("expense_claim", "Expense Claim"),
                            ("salary_adjustment", "Salary Adjustment"),
                            ("new_hire", "New Hire Request"),
                            ("contract", "Contract / Client Proposal"),
                            ("asset_purchase", "Asset Purchase"),
                            ("policy_change", "Policy Change"),
                            ("promotion", "Employee Promotion"),
                            ("general", "General"),
                        ],
                        help_text="The category of action this flow governs",
                        max_length=50,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_flows_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Flow",
                "verbose_name_plural": "Approval Flows",
                "ordering": ["action_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "approval_request_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Request ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(default=1, verbose_name="Current Step"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="user.approvalflow",
                        verbose_name="Approval Flow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Request",
                "verbose_name_plural": "Approval Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("step_order", models.PositiveIntegerField(verbose_name="Step Order")),
                (
                    "step_name",
                    models.CharField(max_length=255, verbose_name="Step Name"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=10,
                        verbose_name="Decision",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="user.approvalrequest",
                        verbose_name="Approval Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Decision",
                "verbose_name_plural": "Approval Decisions",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("step_order", models.PositiveIntegerField(verbose_name="Step Order")),
                (
                    "step_name",
                    models.CharField(max_length=255, verbose_name="Step Name"),
                ),
                (
                    "required_level",
                    models.CharField(
                        help_text="Minimum employee level needed to approve this step",
                        max_length=20,
                        verbose_name="Required Level",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="user.approvalflow",
                        verbose_name="Approval Flow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Flow Step",
                "verbose_name_plural": "Approval Flow Steps",
                "ordering": ["step_order"],
                "unique_together": {("flow", "step_order")},
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["status"], name="user_approv_status_0d5844_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["current_step"], name="user_approv_current_b34572_idx"
            ),
        ),
    ]
