# Generated by Django 5.2.6 on 2026-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_remove_country_default_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="attachment_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the full policy document (uploaded separately)",
                max_length=500,
                null=True,
                verbose_name="Attachment URL",
            ),
        ),
    ]
