# Generated by Django 5.2.6 on 2026-02-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_alter_policy_attachment_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shareholder",
            name="employee",
        ),
    ]
