# Generated by Django 5.2.6 on 2026-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_remove_shareholder_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="offboard_date",
            field=models.DateField(
                blank=True, help_text="Date when employee left the company", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="offboard_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for employee leaving the company",
                null=True,
            ),
        ),
    ]
