# Generated by Django 5.2.6 on 2026-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_employee_offboard_date_employee_offboard_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(help_text="First name", max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(help_text="Last name", max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="profile_picture",
            field=models.URLField(
                blank=True, help_text="Profile picture", max_length=500, null=True
            ),
        ),
    ]
