# Generated by Django 5.2.6 on 2026-03-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_remove_client_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="file_url",
            field=models.URLField(
                blank=True,
                help_text="File URL for the meeting",
                max_length=500,
                null=True,
                verbose_name="File URL",
            ),
        ),
    ]
