# Generated by Django 5.2.6 on 2026-03-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_meeting_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="account_number",
            field=models.CharField(
                blank=True, default="", help_text="Bank account number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(
                blank=True, default="", help_text="Bank name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Job title / designation",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on-probation", "On Probation"),
                    ("on-leave", "On Leave"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                help_text="Current employment status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(
                blank=True, default="", help_text="Work location", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pension_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pension / retirement fund number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_period",
            field=models.PositiveIntegerField(
                blank=True, help_text="Probation period in months", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reporting_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager this employee reports to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="user.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("bi-weekly", "Bi-Weekly"),
                    ("weekly", "Weekly"),
                    ("daily", "Daily"),
                    ("hourly", "Hourly"),
                ],
                default="monthly",
                help_text="Frequency of salary payment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="tax_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tax identification number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_schedule",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Work schedule (e.g. 9am-5pm Mon-Fri)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, default="", help_text="City", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, default="", help_text="Country", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emergency contact full name",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emergency contact phone number",
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Relationship to emergency contact",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", help_text="Employee middle name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(
                blank=True, default="", help_text="Employee nationality", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="other_phone",
            field=models.CharField(
                blank=True,
                help_text="Employee secondary phone number",
                max_length=17,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_email",
            field=models.EmailField(
                blank=True,
                help_text="Employee personal email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True, default="", help_text="State / Province", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True, default="", help_text="Zip / Postal code", max_length=20
            ),
        ),
    ]
