# Generated by Django 5.2.6 on 2026-03-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="recurrences",
            new_name="recurrence",
        ),
    ]
