# Generated by Django 5.2.6 on 2026-03-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_employee_account_number_employee_bank_name_and_more"),
        ("user", "0036_remove_event_reminder_time_event_reminder_offset"),
    ]

    operations = []
