# Generated by Django 5.2.6 on 2026-03-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_merge_20260305_1120"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Document name / title", max_length=255),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to the stored document file", max_length=500
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="File extension (e.g. pdf, doc)",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
