# Generated by Django 5.2.6 on 2026-03-05 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_employeedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When this record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="clientinventoryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="clientinventoryitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="compliancerecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="compliancerecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
    ]
