# Generated by Django 5.2.6 on 2026-03-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0040_review"),
        ("user", "0041_alter_loan_employee_alter_loan_status"),
    ]

    operations = []
