# Generated by Django 5.2.6 on 2026-03-05 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0042_merge_20260305_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="areas_for_improvement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="communication",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Communication rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="development_plan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="initiative",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Initiative rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="job_knowledge",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Job knowledge rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="key_achievements",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="problem_solving",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Problem solving rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="quality_of_work",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quality of work rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_period",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Review period (e.g. Q4 2025)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="teamwork",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Teamwork rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
