# Generated by Django 5.2.6 on 2026-03-06 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_remove_review_comments_remove_review_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="user.employee",
            ),
        ),
    ]
