# Generated by Django 5.2.6 on 2026-03-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_alter_review_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-year", "-quarter"],
                "verbose_name": "Employee Review",
                "verbose_name_plural": "Employee Reviews",
            },
        ),
        migrations.RemoveField(
            model_name="review",
            name="review_period",
        ),
        migrations.AddField(
            model_name="review",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("Q1", "Q1 (Jan–Mar)"),
                    ("Q2", "Q2 (Apr–Jun)"),
                    ("Q3", "Q3 (Jul–Sep)"),
                    ("Q4", "Q4 (Oct–Dec)"),
                ],
                default="Q1",
                help_text="Review quarter (Q1, Q2, Q3, Q4)",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="year",
            field=models.PositiveIntegerField(
                default=2025, help_text="Review year (e.g. 2025)"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["quarter", "year"], name="user_review_quarter_ff2d40_idx"
            ),
        ),
    ]
