# Generated by Django 5.2.6 on 2026-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0045_alter_review_options_remove_review_review_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employer_contribution",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Employer pension contribution percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="hmo_current_plan",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current HMO plan name",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="hmo_dependents_covered",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of dependents covered by HMO"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="hmo_id_number",
            field=models.CharField(
                blank=True, default="", help_text="HMO ID number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pfa_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pension Fund Administrator provider",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="rsa_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Retirement Savings Account number",
                max_length=100,
            ),
        ),
    ]
