# Generated by Django 5.2.6 on 2026-03-09 13:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0046_employee_employer_contribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="branch_role",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("state_headquarters", "State Headquarters"),
                    (
                        "interstate_regional_headquarters",
                        "Inter State Regional Headquarters",
                    ),
                    ("national_headquarters", "National Headquarters"),
                ],
                default="branch",
                max_length=50,
                verbose_name="Branch Role",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, help_text="Date of the review"
            ),
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "estate_name",
                    models.CharField(max_length=255, verbose_name="Estate Name"),
                ),
                (
                    "estate_code",
                    models.CharField(
                        help_text="Unique code e.g. EST-001",
                        max_length=50,
                        unique=True,
                        verbose_name="Estate Code",
                    ),
                ),
                (
                    "estate_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("mixed_use", "Mixed Use"),
                            ("land", "Land"),
                        ],
                        max_length=50,
                        verbose_name="Estate Type",
                    ),
                ),
                (
                    "developer_company_name",
                    models.CharField(
                        max_length=255, verbose_name="Developer / Company Name"
                    ),
                ),
                (
                    "estate_description",
                    models.TextField(verbose_name="Estate Description"),
                ),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                (
                    "city_town",
                    models.CharField(max_length=100, verbose_name="City / Town"),
                ),
                ("precise_address", models.TextField(verbose_name="Precise Address")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "estate_map",
                    models.FileField(
                        blank=True,
                        help_text="PDF or Image (PNG, JPG). Max size 10MB.",
                        null=True,
                        upload_to="estates/maps/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Estate Map / Layout",
                    ),
                ),
                (
                    "has_c_of_o",
                    models.BooleanField(default=False, verbose_name="C of O"),
                ),
                (
                    "has_deed_of_assignment",
                    models.BooleanField(
                        default=False, verbose_name="Deed of Assignment"
                    ),
                ),
                (
                    "has_survey_plan",
                    models.BooleanField(default=False, verbose_name="Survey Plan"),
                ),
                (
                    "zoning_information",
                    models.TextField(
                        blank=True, default="", verbose_name="Zoning Information"
                    ),
                ),
                (
                    "has_planning_permit",
                    models.BooleanField(default=False, verbose_name="Planning Permit"),
                ),
                (
                    "has_building_approval",
                    models.BooleanField(
                        default=False, verbose_name="Building Approval"
                    ),
                ),
                (
                    "has_environmental_clearance",
                    models.BooleanField(
                        default=False, verbose_name="Environmental Clearance"
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price per Square Meter (₦/sqm)",
                    ),
                ),
                (
                    "available_plot_sizes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated sizes e.g. 500, 600, 1000",
                        max_length=500,
                        verbose_name="Available Plot Sizes (sqm)",
                    ),
                ),
                (
                    "min_price_other_properties",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Min Price - Other Properties (₦)",
                    ),
                ),
                (
                    "max_price_other_properties",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Max Price - Other Properties (₦)",
                    ),
                ),
                (
                    "estate_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold_out", "Sold Out"),
                            ("under_development", "Under Development"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        max_length=50,
                        verbose_name="Estate Status",
                    ),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total Area",
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[
                            ("sqm", "Square Meters"),
                            ("hectares", "Hectares"),
                            ("acres", "Acres"),
                            ("sqft", "Square Feet"),
                        ],
                        default="sqm",
                        max_length=20,
                        verbose_name="Area Unit",
                    ),
                ),
                ("has_roads", models.BooleanField(default=False, verbose_name="Roads")),
                (
                    "has_electricity",
                    models.BooleanField(default=False, verbose_name="Electricity"),
                ),
                ("has_water", models.BooleanField(default=False, verbose_name="Water")),
                (
                    "has_fencing",
                    models.BooleanField(default=False, verbose_name="Fencing"),
                ),
                (
                    "has_security",
                    models.BooleanField(default=False, verbose_name="Security"),
                ),
                (
                    "has_drainage",
                    models.BooleanField(default=False, verbose_name="Drainage"),
                ),
                (
                    "has_recreation",
                    models.BooleanField(default=False, verbose_name="Recreation"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estates",
                        to="user.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estate",
                "verbose_name_plural": "Estates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["estate_code"], name="user_estate_estate__aabc7a_idx"
                    ),
                    models.Index(
                        fields=["estate_type"], name="user_estate_estate__0b357c_idx"
                    ),
                    models.Index(
                        fields=["estate_status"], name="user_estate_estate__90bd78_idx"
                    ),
                    models.Index(
                        fields=["country"], name="user_estate_country_6d8d65_idx"
                    ),
                ],
            },
        ),
    ]
