# Generated by Django 5.2.6 on 2026-03-09 15:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0047_create_estate_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "plot_name",
                    models.CharField(
                        help_text="e.g. Plot A-101",
                        max_length=100,
                        verbose_name="Plot Name/Number",
                    ),
                ),
                (
                    "plot_size",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Plot Size (Square Meters)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("under_offer", "Under Offer"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Plot Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="user.estate",
                        verbose_name="Estate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plot",
                "verbose_name_plural": "Plots",
                "ordering": ["plot_name"],
            },
        ),
        migrations.CreateModel(
            name="PlotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="PNG, JPG up to 10MB",
                        upload_to="estates/plots/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="user.plot",
                        verbose_name="Plot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plot Image",
                "verbose_name_plural": "Plot Images",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["estate", "status"], name="user_plot_estate__ff4bc0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plot",
            unique_together={("estate", "plot_name")},
        ),
    ]
