# Generated by Django 5.2.9 on 2026-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0049_rename_plot_to_property"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="property",
            new_name="user_proper_estate__f74701_idx",
            old_name="user_plot_estate__ff4bc0_idx",
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("under_offer", "Under Offer"),
                ],
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
