# Generated by Django 5.2.6 on 2026-03-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0047_alter_branch_branch_role_alter_review_review_date"),
        ("user", "0051_create_cart_models"),
    ]

    operations = []
