# Generated by Django 5.2.6 on 2026-03-11 09:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0052_merge_20260311_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="development_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Development Fee",
            ),
        ),
        migrations.AddField(
            model_name="estate",
            name="is_our_estate",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if this estate is developed by our company.",
                verbose_name="Is Our Estate",
            ),
        ),
        migrations.AddField(
            model_name="estate",
            name="legal_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Legal Fee",
            ),
        ),
        migrations.AddField(
            model_name="estate",
            name="receipt_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Receipt Fee",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="is_our_property",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if this property is developed by our company.",
                verbose_name="Is Our Property",
            ),
        ),
        migrations.AlterField(
            model_name="clientinventoryitem",
            name="total_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total value",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total Value",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="max_price_other_properties",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Max Price - Other Properties",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="min_price_other_properties",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Min Price - Other Properties",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="price_per_sqm",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Price per Square Meter (amount/sqm)",
            ),
        ),
    ]
