# Generated by Django 5.2.6 on 2026-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0054_property_owner_estatepropertyinvoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
