# Generated by Django 5.2.6 on 2026-03-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0055_alter_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estatepropertyinvoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estate_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
