# Generated by Django 5.2.6 on 2026-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0056_alter_estatepropertyinvoice_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="estatepropertyinvoice",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estatepropertyinvoice",
            name="account_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estatepropertyinvoice",
            name="bank_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estatepropertyinvoice",
            name="bank_details_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estatepropertyinvoice",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estatepropertyinvoice",
            name="sort_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="estatepropertyinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("sent", "Sent"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
