# Generated by Django 5.2.6 on 2026-03-11 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0057_estatepropertyinvoice_account_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "step",
                    models.PositiveIntegerField(
                        choices=[(1, "Manager Approval"), (2, "CEO Approval")]
                    ),
                ),
                ("step_name", models.CharField(max_length=50)),
                (
                    "required_level",
                    models.CharField(
                        help_text="Minimum employee level needed for this step.",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="user.estatepropertyinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Approval",
                "verbose_name_plural": "Invoice Approvals",
                "ordering": ["step"],
                "unique_together": {("invoice", "step")},
            },
        ),
    ]
