# Generated by Django 5.2.9 on 2026-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0058_invoiceapproval"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("can_create_project", models.BooleanField(default=False)),
                ("can_view_all_invoice", models.BooleanField(default=False)),
                ("can_edit_employee_data", models.BooleanField(default=False)),
                ("can_delete_project", models.BooleanField(default=False)),
                ("can_approve_timesheets", models.BooleanField(default=False)),
                ("can_generate_financial_reports", models.BooleanField(default=False)),
                ("can_manage_user_permissions", models.BooleanField(default=False)),
                ("can_access_client_files", models.BooleanField(default=False)),
                ("can_send_notifications", models.BooleanField(default=False)),
                ("can_create_client_accounts", models.BooleanField(default=False)),
                ("can_view_audit_logs", models.BooleanField(default=False)),
                ("can_update_project_milestones", models.BooleanField(default=False)),
                ("can_archive_old_projects", models.BooleanField(default=False)),
                ("can_manage_team_schedules", models.BooleanField(default=False)),
                ("can_customize_dashboard", models.BooleanField(default=False)),
                (
                    "can_import_data_from_external_sources",
                    models.BooleanField(default=False),
                ),
                ("can_export_reports_as_pdfs", models.BooleanField(default=False)),
                ("can_configure_system_settings", models.BooleanField(default=False)),
                ("can_assign_roles_to_users", models.BooleanField(default=False)),
                ("can_view_project_summaries", models.BooleanField(default=False)),
                ("can_track_project_budgets", models.BooleanField(default=False)),
                ("can_set_up_alerts_for_deadlines", models.BooleanField(default=False)),
                (
                    "can_facilitate_team_collaboration",
                    models.BooleanField(default=False),
                ),
                ("can_conduct_performance_reviews", models.BooleanField(default=False)),
                ("can_manage_client_feedback", models.BooleanField(default=False)),
                ("can_conduct_surveys_and_polls", models.BooleanField(default=False)),
                ("can_monitor_system_health", models.BooleanField(default=False)),
                (
                    "can_implement_security_protocols",
                    models.BooleanField(default=False),
                ),
                ("can_run_user_activity_reports", models.BooleanField(default=False)),
                ("can_schedule_regular_backups", models.BooleanField(default=False)),
                (
                    "can_manage_external_vendor_contracts",
                    models.BooleanField(default=False),
                ),
                ("can_set_up_payment_gateways", models.BooleanField(default=False)),
                ("can_create_marketing_campaigns", models.BooleanField(default=False)),
                ("can_review_budget_proposals", models.BooleanField(default=False)),
                ("can_manage_inventory_levels", models.BooleanField(default=False)),
                (
                    "can_coordinate_events_and_meetings",
                    models.BooleanField(default=False),
                ),
                ("can_analyze_sales_trends", models.BooleanField(default=False)),
                ("can_supervise_customer_support", models.BooleanField(default=False)),
                ("can_develop_training_programs", models.BooleanField(default=False)),
                ("can_maintain_compliance", models.BooleanField(default=False)),
                ("can_review_legal_agreements", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["-created_at"],
            },
        ),
    ]
