# Generated by Django 5.2.6 on 2026-03-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0059_create_role_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "building_category",
                    models.CharField(
                        choices=[
                            ("duplex", "Duplex"),
                            ("bungalow", "Bungalow"),
                            ("block_of_flats", "Block of Flats"),
                            ("semi_detached", "Semi Detached"),
                            ("terrace", "Terrace"),
                            ("plaza", "Plaza"),
                            ("event_centers", "Event Centers"),
                            ("church", "Church"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "drawing_file",
                    models.URLField(help_text="URL to the uploaded PDF drawing file"),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="File size in MB",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_drawings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawing_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
