# Generated by Django 5.2.6 on 2026-03-13 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0060_drawingbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceapproval",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific user assigned to approve this step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_invoice_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceapproval",
            name="required_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Minimum employee level needed for this step.",
                max_length=20,
            ),
        ),
    ]
