# Generated by Django 5.2.6 on 2026-03-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0061_add_assigned_to_invoice_approval"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="property",
            name="estate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="user.estate",
                verbose_name="Estate",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estate__isnull", False)),
                fields=("estate", "property_name"),
                name="unique_property_name_per_estate",
            ),
        ),
    ]
