# Generated by Django 5.2.6 on 2026-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0063_clientservice_servicerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="client",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
