# Generated by Django 5.2.6 on 2026-03-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0063_add_partner_and_agreement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department_unit",
        ),
        migrations.RemoveField(
            model_name="role",
            name="description",
        ),
        migrations.AddField(
            model_name="employee",
            name="department_units",
            field=models.ManyToManyField(
                blank=True,
                help_text="Department units where employee works",
                related_name="employees",
                to="user.unit",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="user.employeelevel",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles",
                to="user.unit",
            ),
        ),
        migrations.AlterField(
            model_name="employeelevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("intern", "Intern"),
                    ("junior", "Junior"),
                    ("mid_level", "Mid Level"),
                    ("senior", "Senior"),
                    ("high", "High"),
                    ("head", "Head of Department"),
                    ("manager", "Manager"),
                    ("ceo", "Chief Executive Officer"),
                    ("cto", "Chief Technology Officer"),
                    ("cfo", "Chief Financial Officer"),
                    ("clo", "Chief Legal Officer"),
                    ("chro", "Chief Human Resources Officer"),
                    ("cmo", "Chief Marketing Officer"),
                    ("board_member", "Board Member"),
                ],
                help_text="Employee level",
                max_length=20,
                unique=True,
            ),
        ),
    ]
