# Generated by Django 5.2.6 on 2026-03-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0063_add_partner_and_agreement"),
        ("user", "0064_client_address_client_company_name_client_phone"),
    ]

    operations = []
