# Generated by Django 5.2.6 on 2026-03-14 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0065_remove_role_can_access_client_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estate",
            name="estate_map",
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("not-for-sale", "Not for Sale"),
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="EstateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF, Image (PNG, JPG), or Document (DOC, DOCX). Max size 10MB.",
                        upload_to="estates/documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="user.estate",
                        verbose_name="Estate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estate Document",
                "verbose_name_plural": "Estate Documents",
                "ordering": ["created_at"],
            },
        ),
    ]
