# Generated by Django 5.2.6 on 2026-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0066_remove_estate_map_add_estate_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estate",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="estate",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="longitude",
        ),
        migrations.AddField(
            model_name="estate",
            name="boundary",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {lat, lng} points defining the estate boundary polygon. e.g. [{"lat": 6.5244, "lng": 3.3792}, ...]',
                verbose_name="Boundary Coordinates",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="boundary",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {lat, lng} points defining the property boundary polygon. e.g. [{"lat": 6.5244, "lng": 3.3792}, ...]',
                verbose_name="Boundary Coordinates",
            ),
        ),
    ]
