# Generated by Django 5.2.6 on 2026-03-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_budget_current_spend"),
        ("user", "0067_client_alternate_phone_client_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="services.invoice",
            ),
        ),
    ]
