# Generated by Django 5.2.6 on 2026-03-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0067_replace_lat_lng_with_boundary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="roles",
        ),
    ]
