# Generated by Django 5.2.6 on 2026-03-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_budget_current_spend'),
        ('user', '0068_alter_servicerequest_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.invoice'),
        ),
    ]
