# Generated by Django 5.2.6 on 2026-03-14 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0068_remove_employee_roles_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this role only applies to employees in this department.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles",
                to="user.department",
            ),
        ),
        migrations.AlterField(
            model_name="employeelevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("intern", "Intern"),
                    ("junior", "Junior"),
                    ("mid_level", "Mid Level"),
                    ("senior", "Senior"),
                    ("high", "High"),
                    ("head_hr", "Head of Human Resources"),
                    ("head_operations", "Head of Operations"),
                    ("head_marketing", "Head of Marketing"),
                    ("head_finance", "Head of Finance"),
                    ("head_legal", "Head of Legal"),
                    ("head_it", "Head of IT"),
                    ("manager", "Manager"),
                    ("ceo", "Chief Executive Officer"),
                    ("cto", "Chief Technology Officer"),
                    ("cfo", "Chief Financial Officer"),
                    ("clo", "Chief Legal Officer"),
                    ("chro", "Chief Human Resources Officer"),
                    ("cmo", "Chief Marketing Officer"),
                    ("board_member", "Board Member"),
                ],
                help_text="Employee level",
                max_length=20,
                unique=True,
            ),
        ),
    ]
