# Generated by Django 5.2.6 on 2026-03-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0067_client_alternate_phone_client_city_and_more"),
        ("user", "0069_update_levels_and_role_department"),
    ]

    operations = []
