# Generated by Django 5.2.6 on 2026-03-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0069_alter_servicerequest_invoice"),
        ("user", "0070_merge_20260314_1535"),
    ]

    operations = []
