# Generated by Django 5.2.6 on 2026-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0075_merge_20260406_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has enabled two-factor authentication for login",
            ),
        ),
    ]
