# Generated by Django 5.2.6 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_remove_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
