# Generated by Django 5.2.6 on 2026-06-18 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_remove_employee_level"),
        ("user", "0086_rolesuccessplaybookitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleTrainingRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory"),
                            ("continuous", "Continuous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_requirements",
                        to="user.role",
                    ),
                ),
                (
                    "training_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_requirements",
                        to="hr.trainingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "indexes": [
                    models.Index(
                        fields=["role", "sequence"],
                        name="user_roletr_role_id_d01f15_idx",
                    ),
                    models.Index(
                        fields=["role", "requirement_type"],
                        name="user_roletr_role_id_4a45c1_idx",
                    ),
                    models.Index(
                        fields=["role", "training_program"],
                        name="user_roletr_role_id_6ddb3b_idx",
                    ),
                ],
            },
        ),
    ]
