# Generated by Django 5.2.6 on 2026-06-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_roletrainingrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_sops', to='user.role')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='user.sop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'sop'], name='user_roleso_role_id_ee718a_idx'), models.Index(fields=['role', 'is_active'], name='user_roleso_role_id_a3b0db_idx')],
                'unique_together': {('role', 'sop')},
            },
        ),
    ]
