# Generated by Django 5.2.6 on 2026-06-18 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_rolesop'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTargetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_templates', to='user.role')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='user.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_targets', to='user.role')),
                ('role_target_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_targets', to='user.roletargettemplate')),
            ],
            options={
                'ordering': ['-period_start', 'sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='roletargettemplate',
            index=models.Index(fields=['role', 'sequence'], name='user_roleta_role_id_b3adfb_idx'),
        ),
        migrations.AddIndex(
            model_name='roletargettemplate',
            index=models.Index(fields=['role', 'period'], name='user_roleta_role_id_ae60cf_idx'),
        ),
        migrations.AddIndex(
            model_name='roletargettemplate',
            index=models.Index(fields=['role', 'is_active'], name='user_roleta_role_id_6a5bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetarget',
            index=models.Index(fields=['employee', 'period_start'], name='user_employ_employe_b6c606_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetarget',
            index=models.Index(fields=['employee', 'period_end'], name='user_employ_employe_d7608d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetarget',
            index=models.Index(fields=['employee', 'period'], name='user_employ_employe_d2aca2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetarget',
            index=models.Index(fields=['role_target_template', 'period_start', 'period_end'], name='user_employ_role_ta_7b035b_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeetarget',
            constraint=models.UniqueConstraint(fields=('employee', 'role_target_template', 'period_start', 'period_end'), name='uniq_employee_role_template_period'),
        ),
    ]
