# Generated by Django 5.2.6 on 2026-06-22 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0089_roletargettemplate_employeetarget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleCareerPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("requirements", models.TextField(blank=True, default="")),
                (
                    "estimated_duration_months",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "from_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_paths_from",
                        to="user.role",
                    ),
                ),
                (
                    "to_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_paths_to",
                        to="user.role",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "indexes": [
                    models.Index(
                        fields=["from_role", "sequence"],
                        name="user_roleca_from_ro_bafd8b_idx",
                    ),
                    models.Index(
                        fields=["from_role", "is_active"],
                        name="user_roleca_from_ro_53f3e0_idx",
                    ),
                    models.Index(
                        fields=["from_role", "to_role"],
                        name="user_roleca_from_ro_69e47f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_role", "to_role"),
                        name="uniq_role_career_path_edge",
                    )
                ],
            },
        ),
    ]
