# Generated by Django 5.2.6 on 2026-06-22 07:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_remove_employee_level'),
        ('user', '0090_rolecareerpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleKPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('tracking_mode', models.CharField(choices=[('manual', 'Manual'), ('system', 'System')], max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='hr.kpimetric')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_kpis', to='user.role')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('metric_name', models.CharField(max_length=200)),
                ('metric_unit', models.CharField(max_length=20)),
                ('tracking_mode', models.CharField(choices=[('manual', 'Manual'), ('system', 'System')], max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to='user.employee')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_kpi_records', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to='hr.kpimetric')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_kpi_records', to='user.role')),
                ('role_kpi_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to='user.rolekpimetric')),
            ],
            options={
                'ordering': ['-period_start', 'sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='rolekpimetric',
            index=models.Index(fields=['role', 'sequence'], name='user_rolekp_role_id_51e3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='rolekpimetric',
            index=models.Index(fields=['role', 'tracking_mode'], name='user_rolekp_role_id_296dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='rolekpimetric',
            index=models.Index(fields=['role', 'period'], name='user_rolekp_role_id_84d9d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolekpimetric',
            constraint=models.UniqueConstraint(fields=('role', 'metric'), name='uniq_role_kpi_metric'),
        ),
        migrations.AddIndex(
            model_name='employeekpirecord',
            index=models.Index(fields=['employee', 'period_start'], name='user_employ_employe_244de8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeekpirecord',
            index=models.Index(fields=['employee', 'period'], name='user_employ_employe_455661_idx'),
        ),
        migrations.AddIndex(
            model_name='employeekpirecord',
            index=models.Index(fields=['employee', 'tracking_mode'], name='user_employ_employe_b8024e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeekpirecord',
            index=models.Index(fields=['role_kpi_metric', 'period_start', 'period_end'], name='user_employ_role_kp_f4521f_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeekpirecord',
            constraint=models.UniqueConstraint(fields=('employee', 'role_kpi_metric', 'period_start', 'period_end'), name='uniq_employee_role_kpi_period'),
        ),
    ]
