# Generated by Django 5.2.6 on 2026-08-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0083_workflow_rule"),
        ("user", "0094_brokeragelisting_brokeragelistingimage_and_more"),
    ]

    operations = []
