# Generated by Codex

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("services", "0035_payment_finance_account_and_proof"),
        ("user", "0095_merge_20260808_2105"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsubmission",
            name="confirmed_payment",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_submission", to="services.payment"),
        ),
        migrations.AddField(
            model_name="paymentsubmission",
            name="finance_account",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payment_submissions", to="finance.financeaccount"),
        ),
        migrations.AddField(
            model_name="paymentsubmission",
            name="receiving_account_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentsubmission",
            name="submitted_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payment_submissions_created", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="paymentsubmission",
            name="submitted_by_type",
            field=models.CharField(choices=[("client", "Client"), ("staff", "Staff")], default="client", max_length=20),
        ),
        migrations.AddField(
            model_name="paymentsubmission",
            name="transaction_reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
