# Generated by Django 5.2.6 on 2026-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0097_alter_auditlog_audit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="estate_map_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Uploaded PDF or hosted link for the estate layout drawing.",
                max_length=1000,
                verbose_name="Estate Map URL",
            ),
        ),
        migrations.AddField(
            model_name="estate",
            name="virtual_tour_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hosted 3D walkthrough or map-based virtual tour link.",
                max_length=1000,
                verbose_name="Virtual Tour URL",
            ),
        ),
    ]
