# Generated by Django 5.2.6 on 2026-08-26 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0101_estate_sales_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("full_payment", "Full Payment"),
                            ("reservation", "Reservation"),
                            ("installment", "Installment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "agreed_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "reservation_threshold_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "reservation_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "installment_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "payment_window_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_approval", "Awaiting Approval"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("reserved", "Reserved"),
                            ("installment_active", "Installment Active"),
                            ("fully_paid", "Fully Paid"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="awaiting_approval",
                        max_length=30,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_purchases",
                        to="user.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_property_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_purchases",
                        to="user.estatepropertyinvoice",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="user.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Purchase",
                "verbose_name_plural": "Property Purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "status"],
                        name="user_proper_propert_0eed47_idx",
                    ),
                    models.Index(
                        fields=["client", "status"],
                        name="user_proper_client__510b2e_idx",
                    ),
                    models.Index(
                        fields=["payment_window_expires_at"],
                        name="user_proper_payment_f72651_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "awaiting_approval",
                                    "awaiting_payment",
                                    "reserved",
                                    "installment_active",
                                ],
                            )
                        ),
                        fields=("property",),
                        name="unique_active_property_purchase",
                    )
                ],
            },
        ),
    ]
