# Generated by Django 5.2.6 on 2026-08-26 20:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_real_estate_revenue_account"),
        ("user", "0102_property_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("purpose_type", models.CharField(max_length=80)),
                ("purpose_id", models.CharField(max_length=80)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accounting_total_due",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "accounting_total_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "accounting_prior_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("revenue_account_code", models.CharField(max_length=30)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to="user.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("provider", models.CharField(max_length=50)),
                ("idempotency_key", models.CharField(max_length=160)),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "failure_code",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("failure_message", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="user.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfirmedReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("provider", models.CharField(max_length=50)),
                ("provider_transaction_reference", models.CharField(max_length=180)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("paid_at", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("finance_posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application_reference",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finance_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="central_confirmed_receipts",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "finance_journal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="central_confirmed_receipt",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_receipt",
                        to="user.paymentattempt",
                    ),
                ),
                (
                    "intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_receipt",
                        to="user.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProviderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("event_key", models.CharField(max_length=180)),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("payload", models.JSONField(default=dict)),
                ("payload_digest", models.CharField(max_length=64)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_events",
                        to="user.paymentattempt",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_events",
                        to="user.paymentintent",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_events",
                        to="user.confirmedreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["purpose_type", "purpose_id"],
                name="user_paymen_purpose_81384d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["status", "expires_at"], name="user_paymen_status_c3c047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["currency", "status"], name="user_paymen_currenc_4b74bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["intent", "status"], name="user_paymen_intent__804ef1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["provider", "status"], name="user_paymen_provide_d64b01_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                fields=("provider", "idempotency_key"),
                name="uniq_pay_attempt_provider_idem",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_reference", ""), _negated=True),
                fields=("provider", "provider_reference"),
                name="uniq_pay_attempt_provider_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="confirmedreceipt",
            index=models.Index(
                fields=["provider", "paid_at"], name="user_confir_provide_912a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="confirmedreceipt",
            index=models.Index(
                fields=["applied_at"], name="user_confir_applied_dc47be_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmedreceipt",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_transaction_reference"),
                name="uniq_confirmed_receipt_provider_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentproviderevent",
            index=models.Index(
                fields=["provider", "status"], name="user_paymen_provide_a41533_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentproviderevent",
            index=models.Index(
                fields=["intent", "status"], name="user_paymen_intent__f0c9dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentproviderevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_key"), name="uniq_pay_event_provider_key"
            ),
        ),
    ]
