# Generated by Django 5.2.6 on 2026-03-06 14:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        ("user", "0046_employee_employer_contribution_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("surveying", "Surveying"),
                            ("construction", "Construction"),
                            ("it", "Information Technology (IT)"),
                            ("civil_engineering", "Civil Engineering"),
                            ("mechanical_engineering", "Mechanical Engineering"),
                            ("electrical_engineering", "Electrical Engineering"),
                            ("environmental_engineering", "Environmental Engineering"),
                            ("project_management", "Project Management"),
                            ("property_sale_rent", "Property Sale/Rent"),
                            ("maintenance", "Maintenance & Technical Support"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Event Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("trade_show", "Trade Show"),
                            ("webinar", "Webinar"),
                            ("career_fair", "Career Fair"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("networking", "Networking"),
                            ("product_launch", "Product Launch"),
                            ("meetup", "Meetup"),
                            ("exhibition", "Exhibition"),
                        ],
                        max_length=50,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Venue Name"
                    ),
                ),
                (
                    "venue_address",
                    models.TextField(blank=True, verbose_name="Venue Address"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Online Event"),
                ),
                (
                    "online_platform",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Online Platform"
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(blank=True, verbose_name="Meeting URL"),
                ),
                ("event_date", models.DateField(verbose_name="Event Date")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Duration (Hours)",
                    ),
                ),
                (
                    "max_registrations",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Maximum Registrations"
                    ),
                ),
                (
                    "current_registrations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Current Registrations"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Registration Deadline"
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Registration Fee",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, verbose_name="Allow Registration"
                    ),
                ),
                (
                    "banner_image",
                    models.URLField(blank=True, null=True, verbose_name="Banner Image"),
                ),
                (
                    "thumbnail",
                    models.URLField(blank=True, null=True, verbose_name="Thumbnail"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="Tags"),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Target Audience"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Event"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Public Event"),
                ),
                (
                    "send_reminders",
                    models.BooleanField(default=True, verbose_name="Send Reminders"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="event_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["event_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Registration Status",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Confirmation Code",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attendee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="services.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("food", "Food"),
                            ("accommodation", "Accommodation"),
                            ("equipment", "Equipment"),
                            ("utilities", "Utilities"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7.50"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="svc_invoices",
                        to="user.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budget amount",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("cheque", "Cheque"),
                        ],
                        default="transfer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="operations.project",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="services.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-budget_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="services.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the marketing campaign",
                        max_length=255,
                        verbose_name="Campaign Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the campaign target audience or purpose",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("social_media", "Social Media"),
                            ("email", "Email"),
                            ("search", "Search"),
                            ("display", "Display"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Marketing Channel",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of times the campaign was displayed",
                        verbose_name="Impressions",
                    ),
                ),
                (
                    "ctr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Click-through rate as a percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="CTR (%)",
                    ),
                ),
                (
                    "roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Return on Investment as a percentage",
                        max_digits=6,
                        verbose_name="ROI (%)",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Campaign completion percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Progress (%)",
                    ),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget allocated for the campaign",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Budget Allocated",
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount spent so far",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Budget Spent",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
            ],
            options={
                "verbose_name": "Marketing Campaign",
                "verbose_name_plural": "Marketing Campaigns",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="services_ma_status_7e6679_idx",
                    ),
                    models.Index(
                        fields=["channel"], name="services_ma_channel_43315c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("transaction_reference", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="services.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Property Name"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("land", "Land"),
                        ],
                        max_length=50,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("rent", "For Rent"),
                            ("lease", "For Lease"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                ("location", models.TextField(verbose_name="Location/Address")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price",
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Size (sqm)",
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(default=0)),
                ("bathrooms", models.PositiveIntegerField(default=0)),
                ("parking_spaces", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Property Images (URLs)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("reserved", "Reserved"),
                            ("pending", "Pending"),
                            ("off_market", "Off Market"),
                        ],
                        default="available",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="user.client",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(help_text="e.g., '3-5 weeks'", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("valid_until", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="user.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="services.service",
            ),
        ),
        migrations.CreateModel(
            name="ServiceLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("contacted", "Contacted"),
                            ("proposal_sent", "Proposal Sent"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_leads",
                        to="user.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_service_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="services.servicelead",
            ),
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_link", models.URLField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_service_orders",
                        to="user.employee",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="user.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_service_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="services.quote",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="services.serviceorder",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="services.property",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="services.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Content title or headline",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog_post", "Blog Post"),
                            ("social_media", "Social Media"),
                            ("video", "Video"),
                            ("infographic", "Infographic"),
                            ("newsletter", "Newsletter"),
                            ("article", "Article"),
                        ],
                        default="blog_post",
                        max_length=50,
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("website", "Website"),
                            ("medium", "Medium"),
                            ("youtube", "YouTube"),
                        ],
                        help_text="Platform where content is published",
                        max_length=50,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Main content/text",
                        verbose_name="Content Body",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short description or summary",
                        max_length=500,
                        verbose_name="Excerpt",
                    ),
                ),
                (
                    "featured_image",
                    models.URLField(
                        blank=True, null=True, verbose_name="Featured Image"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Views")),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Likes")),
                (
                    "shares",
                    models.PositiveIntegerField(default=0, verbose_name="Shares"),
                ),
                (
                    "comments",
                    models.PositiveIntegerField(default=0, verbose_name="Comments"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published Date"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled Date"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="External URL"),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Keywords"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="Tags"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Category"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="Allow Comments"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_content",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Content",
                "ordering": ["-published_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_date"],
                        name="services_co_status_a2ad51_idx",
                    ),
                    models.Index(
                        fields=["content_type", "platform"],
                        name="services_co_content_897e4a_idx",
                    ),
                    models.Index(
                        fields=["author", "-created_at"],
                        name="services_co_author__a192c3_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "event_date"], name="services_ev_status_1fe462_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "-event_date"],
                name="services_ev_event_t_2916a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer", "-created_at"],
                name="services_ev_organiz_485237_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "attendee")},
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "-date"], name="services_ex_user_id_331af9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["status"], name="services_ex_status_0845f4_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="services_ex_categor_735195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["invoice"], name="services_bu_invoice_1be964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["project"], name="services_bu_project_d4af80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["status"], name="services_bu_status_f321d1_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "category"], name="services_pr_status_bef2fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["client"], name="services_pr_client__88afd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type"], name="services_pr_propert_092d17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["client"], name="services_qu_client__70c513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="services_qu_status_bfcddd_idx"),
        ),
        migrations.AddIndex(
            model_name="servicelead",
            index=models.Index(
                fields=["client"], name="services_se_client__c595b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicelead",
            index=models.Index(fields=["status"], name="services_se_status_f9b7ba_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["client"], name="services_se_client__3b997b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["order_status"], name="services_se_order_s_77990e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["payment_status"], name="services_se_payment_19894b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client"], name="services_in_client__3afad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="services_in_status_d075eb_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "-created_at"], name="services_do_user_id_f34782_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["order"], name="services_do_order_i_040141_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["property"], name="services_do_propert_b20282_idx"
            ),
        ),
    ]
