# Generated by Django 5.2.6 on 2026-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_expense_attachment_expense_department_expense_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
