# Generated by Django 5.2.6 on 2026-03-11 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_expense_status'),
        ('user', '0047_alter_branch_branch_role_alter_review_review_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='services_bu_invoice_1be964_idx',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='services_bu_project_d4af80_idx',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='services_bu_status_f321d1_idx',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='budget_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='project',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='status',
        ),
        migrations.AddField(
            model_name='budget',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='current_spend',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Amount of the budget that has been spent', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_period',
            field=models.CharField(blank=True, choices=[('Q1 2026', 'Q1 2026'), ('Q2 2026', 'Q2 2026'), ('Q3 2026', 'Q3 2026'), ('Q4 2026', 'Q4 2026')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_period'], name='services_bu_fiscal__61ee8d_idx'),
        ),
    ]
