# Generated by Django 5.2.6 on 2026-03-11 14:54

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_budget_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="current_spend",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount of the budget that has been spent",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
