# Generated by Django 5.2.6 on 2026-03-11 15:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_budget_current_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='current_spend',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Amount of the budget that has been spent', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
