# Generated by Django 5.2.6 on 2026-07-14 10:37

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_funnelstage_pipelinestage_inquiry_followup_deal_and_more"),
        ("user", "0093_employeetargetreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("real_estate", "Real Estate"),
                            ("engineering", "Engineering"),
                            ("surveying", "Land Surveying"),
                            ("benji", "Benji"),
                            ("ict", "ICT / Tech"),
                            ("agriculture", "Agriculture"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("facebook_ad", "Facebook Ad"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("referral", "Referral"),
                            ("walk_in", "Walk-in"),
                            ("website_form", "Website Form"),
                            ("linkedin", "LinkedIn"),
                            ("field_outreach", "Field Outreach"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("budget_range", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiation", "Negotiation"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("dormant", "Dormant"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("first_contact_at", models.DateTimeField(blank=True, null=True)),
                ("last_contact_at", models.DateTimeField(blank=True, null=True)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("next_action", models.CharField(blank=True, max_length=255)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_marketing_leads",
                        to="user.employee",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_leads",
                        to="user.branch",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="services.marketingcampaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_marketing_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "division"],
                        name="services_le_status_7b86b9_idx",
                    ),
                    models.Index(
                        fields=["source"], name="services_le_source_b9ad25_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="services_le_assigne_eb0d74_idx"
                    ),
                    models.Index(
                        fields=["campaign"], name="services_le_campaig_bff1ca_idx"
                    ),
                    models.Index(
                        fields=["next_follow_up_at"],
                        name="services_le_next_fo_91185e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="services_le_created_58f275_idx"
                    ),
                ],
            },
        ),
    ]
