# Generated by Django 5.2.6 on 2026-07-15 10:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_turnaroundplan_turnaroundaction_and_more'),
        ('user', '0093_employeetargetreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_objectives', to='user.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revenue_objectives', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_revenue_objectives', to='user.employee')),
            ],
            options={
                'ordering': ['period_start', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RevenueKeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('title', models.CharField(max_length=255)),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('progress_mode', models.CharField(choices=[('manual', 'Manual'), ('employee_target', 'Employee Target'), ('employee_kpi', 'Employee KPI')], default='manual', max_length=30)),
                ('source_metric_key', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track'), ('completed', 'Completed')], default='at_risk', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('linked_employee_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_key_results', to='user.employeetarget')),
                ('linked_kpi_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_key_results', to='user.employeekpirecord')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='services.revenueobjective')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='revenueobjective',
            index=models.Index(fields=['period_start', 'period_end'], name='services_re_period__f73b78_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueobjective',
            index=models.Index(fields=['status', 'period_start'], name='services_re_status_126175_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueobjective',
            index=models.Index(fields=['branch', 'status'], name='services_re_branch__9de2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueobjective',
            index=models.Index(fields=['owner'], name='services_re_owner_i_8caceb_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuekeyresult',
            index=models.Index(fields=['objective', 'sort_order'], name='services_re_objecti_437489_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuekeyresult',
            index=models.Index(fields=['progress_mode'], name='services_re_progres_152216_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuekeyresult',
            index=models.Index(fields=['status'], name='services_re_status_b3b2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuekeyresult',
            index=models.Index(fields=['linked_employee_target'], name='services_re_linked__ea1599_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuekeyresult',
            index=models.Index(fields=['linked_kpi_record'], name='services_re_linked__f54701_idx'),
        ),
    ]
