# Generated by Django 5.2.6 on 2026-07-16 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_revenueobjective_revenuekeyresult_and_more'),
        ('user', '0093_employeetargetreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('from_stage', models.CharField(blank=True, choices=[('discovery', 'Discovery'), ('evaluation', 'Evaluation'), ('intent', 'Intent'), ('purchase', 'Purchase'), ('loyalty', 'Loyalty')], max_length=30)),
                ('to_stage', models.CharField(blank=True, choices=[('discovery', 'Discovery'), ('evaluation', 'Evaluation'), ('intent', 'Intent'), ('purchase', 'Purchase'), ('loyalty', 'Loyalty')], max_length=30)),
                ('event_type', models.CharField(choices=[('initial', 'Initial'), ('transition', 'Transition'), ('terminal', 'Terminal')], default='transition', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('division', models.CharField(blank=True, default='', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_funnel_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_funnel_events', to='user.branch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_funnel_events', to='services.marketingcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='services.lead')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['lead', 'occurred_at'], name='services_le_lead_id_c040cf_idx'), models.Index(fields=['to_stage', 'occurred_at'], name='services_le_to_stag_33da97_idx'), models.Index(fields=['event_type', 'occurred_at'], name='services_le_event_t_d2a0ba_idx'), models.Index(fields=['branch', 'division'], name='services_le_branch__12855a_idx'), models.Index(fields=['source'], name='services_le_source_504af5_idx'), models.Index(fields=['campaign'], name='services_le_campaig_a561b4_idx')],
            },
        ),
    ]
