# Generated by Django 5.2.6 on 2026-07-29 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_emailmarketingcampaign_emailmarketingrecipient"),
        ("user", "0093_employeetargetreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingMeetingContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("general_marketing", "General Marketing"),
                            ("pre_campaign_planning", "Pre-Campaign Planning"),
                            ("campaign_kickoff", "Campaign Kickoff"),
                            ("creative_review", "Creative Review"),
                            ("live_optimization_review", "Live Optimization Review"),
                            ("sales_alignment", "Sales Alignment"),
                            ("budget_review", "Budget Review"),
                            (
                                "partner_influencer_briefing",
                                "Partner / Influencer Briefing",
                            ),
                            ("post_campaign_analysis", "Post-Campaign Analysis"),
                            ("crisis_issue", "Crisis / Issue"),
                            ("one_on_one_coaching", "One-on-One Coaching"),
                        ],
                        default="general_marketing",
                        max_length=50,
                    ),
                ),
                ("facilitator", models.CharField(blank=True, max_length=120)),
                ("recorder", models.CharField(blank=True, max_length=120)),
                ("pre_read", models.TextField(blank=True)),
                ("expected_outcome", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_meeting_contexts",
                        to="services.marketingcampaign",
                    ),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_context",
                        to="user.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["-meeting__meeting_date", "-meeting__meeting_time"],
            },
        ),
        migrations.CreateModel(
            name="MarketingMeetingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("owner_name", models.CharField(blank=True, max_length=120)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_marketing_meeting_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_meeting_actions",
                        to="user.employee",
                    ),
                ),
                (
                    "meeting_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="services.marketingmeetingcontext",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="campaigndecision",
            name="source_meeting_context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_decisions",
                to="services.marketingmeetingcontext",
            ),
        ),
        migrations.AddIndex(
            model_name="marketingmeetingcontext",
            index=models.Index(
                fields=["campaign", "meeting_type"],
                name="services_ma_campaig_885490_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketingmeetingcontext",
            index=models.Index(
                fields=["meeting_type"], name="services_ma_meeting_149469_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketingmeetingaction",
            index=models.Index(
                fields=["status", "due_date"], name="services_ma_status_7b6374_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketingmeetingaction",
            index=models.Index(
                fields=["priority"], name="services_ma_priorit_d12204_idx"
            ),
        ),
    ]
