# Generated by Django 5.2.6 on 2026-07-29 09:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_marketingmeetingcontext_marketingmeetingaction_and_more"),
        ("user", "0093_employeetargetreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TraditionalMediaPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement_type",
                    models.CharField(
                        choices=[
                            ("billboard", "Billboard"),
                            ("radio", "Radio"),
                            ("television", "Television"),
                            ("led_screen", "LED Screen"),
                            ("print_newspaper", "Print / Newspaper"),
                            ("field_activation", "Field Activation"),
                            ("branded_vehicle", "Branded Vehicle"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("rented", "Rented"),
                            ("company_owned", "Company-owned"),
                            ("partnership", "Partnership"),
                        ],
                        default="rented",
                        max_length=30,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("proof_url", models.URLField(blank=True, max_length=1000)),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("real_estate", "Real Estate"),
                            ("engineering", "Engineering"),
                            ("surveying", "Land Surveying"),
                            ("benji", "Benji"),
                            ("ict", "ICT / Tech"),
                            ("agriculture", "Agriculture"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traditional_media_placements",
                        to="user.branch",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traditional_media_placements",
                        to="services.marketingcampaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_traditional_media_placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["end_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["placement_type", "status"],
                        name="services_tr_placeme_8c3978_idx",
                    ),
                    models.Index(
                        fields=["ownership"], name="services_tr_ownersh_884b2a_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="services_tr_end_dat_7d63b8_idx"
                    ),
                    models.Index(
                        fields=["campaign"], name="services_tr_campaig_05c77c_idx"
                    ),
                    models.Index(
                        fields=["branch", "division"],
                        name="services_tr_branch__c194d1_idx",
                    ),
                ],
            },
        ),
    ]
