# Generated by Django 5.2.6 on 2026-08-04 07:54

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_service_client_visibility_service_code_and_more"),
        ("user", "0093_employeetargetreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("request_form_version", models.PositiveIntegerField(default=1)),
                (
                    "pricing_config_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "workflow_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company"),
                            ("family_group", "Family / Group"),
                            ("cooperative", "Cooperative"),
                            ("government", "Government"),
                            ("partner_realtor", "Partner / Realtor"),
                            ("other", "Other"),
                        ],
                        default="individual",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("client_portal", "Client Portal"),
                            ("sales_crm", "Sales / CRM"),
                            ("walk_in", "Walk-in"),
                            ("meta_ads", "Meta Ads"),
                            ("whatsapp", "WhatsApp"),
                            ("referral", "Referral"),
                            ("external_realtor", "External Realtor"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        default="client_portal",
                        max_length=30,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("awaiting_client", "Awaiting Client"),
                            ("site_assessment", "Site Assessment"),
                            ("quoted", "Quoted"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("next_action", models.CharField(blank=True, max_length=255)),
                ("scope_summary", models.TextField(blank=True)),
                ("answers_snapshot", models.JSONField(blank=True, default=dict)),
                ("form_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commercial_service_requests",
                        to="user.branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_service_requests",
                        to="user.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crm_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="services.lead",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_service_requests",
                        to="user.employee",
                    ),
                ),
                (
                    "pricing_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="services.servicepricingconfig",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="services.quote",
                    ),
                ),
                (
                    "request_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="services.servicerequestform",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_requests",
                        to="services.service",
                    ),
                ),
                (
                    "service_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="services.servicelead",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subservice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commercial_requests",
                        to="services.servicesubservice",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="services.serviceworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("request_created", "Request Created"),
                            ("control_update", "Control Update"),
                            ("assessment_scheduled", "Assessment Scheduled"),
                            ("assessment_result", "Assessment Result"),
                            ("document_received", "Document Received"),
                            ("internal_note", "Internal Note"),
                            ("phone_call", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("quote_prepared", "Quote Prepared"),
                            ("status_change", "Status Change"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("successful", "Successful"),
                            ("no_response", "No Response"),
                            ("information_required", "Information Required"),
                            ("follow_up_scheduled", "Follow-up Scheduled"),
                            ("escalated", "Escalated"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_applicable",
                        max_length=40,
                    ),
                ),
                ("note", models.TextField()),
                ("next_action", models.CharField(blank=True, max_length=255)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_request_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="services.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("money", "Money"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("multiselect", "Multi-select"),
                            ("checkbox", "Checkbox"),
                            ("file", "File"),
                            ("location", "Location"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_answers",
                        to="services.servicerequestfield",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="services.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.SlugField(blank=True, max_length=100)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_url", models.URLField(max_length=1000)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="services.servicerequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_service_request_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["client", "status"], name="services_se_client__2c6fb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["service", "status"], name="services_se_service_a7707a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["branch", "status"], name="services_se_branch__3de003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["owner", "status"], name="services_se_owner_i_5cb58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "priority"], name="services_se_status_14d62b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["due_date"], name="services_se_due_dat_c94cdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["created_at"], name="services_se_created_fe46d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestactivity",
            index=models.Index(
                fields=["request", "activity_type"],
                name="services_se_request_f9fc5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestactivity",
            index=models.Index(
                fields=["next_follow_up_at"], name="services_se_next_fo_def409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestanswer",
            index=models.Index(
                fields=["request", "field_key"], name="services_se_request_434806_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequestanswer",
            constraint=models.UniqueConstraint(
                fields=("request", "field_key"),
                name="unique_service_request_answer_key",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestattachment",
            index=models.Index(
                fields=["request", "field_key"], name="services_se_request_3cdac5_idx"
            ),
        ),
    ]
