# Generated by Django 5.2.6 on 2026-08-07 12:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_alter_serviceorderactivity_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('feedback_type', models.CharField(choices=[('completion', 'Completion'), ('milestone', 'Milestone'), ('complaint', 'Complaint'), ('defect_rework', 'Defect / Rework'), ('testimonial', 'Testimonial'), ('referral', 'Referral')], max_length=30)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('action_required', 'Action Required'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='services.serviceorder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='services_cl_status_09a27c_idx'), models.Index(fields=['feedback_type'], name='services_cl_feedbac_9c407a_idx'), models.Index(fields=['order'], name='services_cl_order_i_336e49_idx'), models.Index(fields=['-created_at'], name='services_cl_created_201af6_idx')],
            },
        ),
    ]
