# Generated by Django 5.2.6 on 2026-08-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_expense_approved_at_expense_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
