# Generated by Django 5.2.6 on 2026-03-06 14:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0046_employee_employer_contribution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("count", "Count"),
                            ("currency", "Currency"),
                            ("rating", "Rating"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "kpi_metrics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the award (e.g., Employee of the Month)",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("employee_of_the_month", "Employee of the month"),
                            ("state_excellence_winner", "State excellence winner"),
                            (
                                "best_branch_representative",
                                "Best branch representative",
                            ),
                            ("regional_leader", "Regional leader"),
                            ("dependable_team_member", "Dependable team member"),
                            ("other", "Other"),
                        ],
                        help_text="Category of the award (e.g., Monthly Recognition, Excellence)",
                        max_length=100,
                    ),
                ),
                (
                    "date_awarded",
                    models.DateField(help_text="Date the award was given"),
                ),
                (
                    "rank_level",
                    models.CharField(
                        choices=[
                            ("branch", "Branch"),
                            ("state", "State"),
                            ("inter-state-region", "Inter state region"),
                            ("national", "National"),
                        ],
                        help_text="Rank or level of the award (e.g., Enugu State, Headquarters)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or reason for the award",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "db_table": "awards",
                "ordering": ["-date_awarded"],
                "indexes": [
                    models.Index(
                        fields=["date_awarded"], name="awards_date_aw_4afe15_idx"
                    ),
                    models.Index(fields=["category"], name="awards_categor_61f28d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_title", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("vacancy_count", models.PositiveIntegerField(default=1)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_postings",
                        to="user.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_postings",
                        to="user.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "db_table": "job_postings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("portolio_url", models.URLField(blank=True, null=True)),
                ("resume", models.URLField(blank=True, null=True)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "current_job_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("shortlisted", "Shortlisted"),
                            ("interviewed", "Interviewed"),
                            ("offered", "Offered"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=50,
                    ),
                ),
                (
                    "highest_education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor Degree"),
                            ("master", "Master Degree"),
                            ("doctorate", "Doctorate"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("company_website", "Company Website"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to="hr.jobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant",
                "verbose_name_plural": "Applicants",
                "db_table": "applicants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_templates",
                        to="user.department",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_templates",
                        to="user.employeelevel",
                    ),
                ),
            ],
            options={
                "db_table": "kpi_templates",
                "ordering": ["department", "level"],
            },
        ),
        migrations.CreateModel(
            name="KPITemplateMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight as a percentage (all weights in a template should sum to 100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target value for this metric",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_assignments",
                        to="hr.kpimetric",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_metrics",
                        to="hr.kpitemplate",
                    ),
                ),
            ],
            options={
                "db_table": "kpi_template_metrics",
                "ordering": ["-weight"],
            },
        ),
        migrations.AddField(
            model_name="kpitemplate",
            name="metrics",
            field=models.ManyToManyField(
                related_name="templates",
                through="hr.KPITemplateMetric",
                to="hr.kpimetric",
            ),
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("sick_leave", "Sick Leave"),
                            ("annual_leave", "Annual Leave"),
                            ("casual_leave", "Casual Leave"),
                            ("maternity_leave", "Maternity Leave"),
                            ("paternity_leave", "Paternity Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                            ("compassionate_leave", "Compassionate Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to="user.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyScorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "attendance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "task_delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "report_accuracy_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "brand_contribution_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "training_progress_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "target_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "target_achievement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("ranking", models.IntegerField(blank=True, null=True)),
                ("is_auto_generated", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_scorecards",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "db_table": "monthly_scorecards",
                "ordering": ["-year", "-month", "-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("manager_comments", models.TextField()),
                ("promotion_required", models.BooleanField(default=False)),
                ("training_required", models.BooleanField(default=False)),
                ("salary_increase", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_received",
                        to="user.employee",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_given",
                        to="user.employee",
                    ),
                ),
                (
                    "scorecard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="hr.monthlyscorecard",
                    ),
                ),
            ],
            options={
                "db_table": "employee_evaluations",
                "ordering": ["-year", "-month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfferLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("standard_full_time", "Standard Full-Time"),
                            ("standard_part_time", "Standard Part-Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="standard_full_time",
                        max_length=50,
                    ),
                ),
                ("annual_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateTimeField()),
                ("letter_content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_letters",
                        to="hr.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Letter",
                "verbose_name_plural": "Offer Letters",
                "db_table": "offer_letters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payroll_period",
                    models.CharField(
                        help_text="e.g., July 2025, Q1 2025, etc.", max_length=50
                    ),
                ),
                (
                    "allowances",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Allowances breakdown as key-value pairs",
                    ),
                ),
                (
                    "deductions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Deductions breakdown as key-value pairs",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("disbursement_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payroll Records",
                "db_table": "payroll",
                "ordering": ["-disbursement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_date", models.DateField()),
                (
                    "review_period",
                    models.CharField(
                        choices=[
                            ("q1", "Q1"),
                            ("q2", "Q2"),
                            ("q3", "Q3"),
                            ("q4", "Q4"),
                        ],
                        help_text="e.g., Q1 2025, H1 2025, 2025, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        help_text="Employee's key strengths and accomplishments"
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(help_text="Areas where the employee can improve"),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Additional feedback and comments",
                        null=True,
                    ),
                ),
                (
                    "employee_comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional feedback and comments",
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="user.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "db_table": "performance_reviews",
                "ordering": ["-review_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_name", models.CharField(db_index=True, max_length=255)),
                (
                    "provider",
                    models.CharField(
                        help_text="Training provider or organization", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the training program"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost of the training program",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all_employees", "All Employees"),
                            ("management", "Management"),
                            ("new_hires", "New Hires"),
                            ("department_specific", "Department Specific"),
                            ("leadership_team", "Leadership Team"),
                            ("technical_staff", "Technical Staff"),
                            ("sales_team", "Sales Team"),
                            ("customer_service", "Customer Service"),
                        ],
                        default="all_employees",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Program",
                "verbose_name_plural": "Training Programs",
                "db_table": "training_programs",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program_name", "start_date"],
                        name="training_pr_program_110536_idx",
                    ),
                    models.Index(
                        fields=["status", "start_date"],
                        name="training_pr_status_e87c18_idx",
                    ),
                    models.Index(
                        fields=["target_audience"],
                        name="training_pr_target__b419b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Name of the asset", max_length=255),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("printer", "Printer"),
                            ("vehicle", "Vehicle"),
                            ("furniture", "Furniture"),
                            ("equipment", "Equipment"),
                            ("other", "Other"),
                        ],
                        default="equipment",
                        max_length=50,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "branch",
                    models.CharField(
                        help_text="Branch where the asset is located", max_length=100
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_use", "In Use"),
                            ("maintenance", "Maintenance"),
                            ("available", "Available"),
                            ("retired", "Retired"),
                            ("lost_stolen", "Lost/Stolen"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=50,
                    ),
                ),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "documents",
                    models.URLField(
                        blank=True,
                        help_text="Upload invoice, warranty, manual, etc.",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_assets",
                        to="user.employee",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_assets",
                        to="user.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="assets_status_326766_idx"),
                    models.Index(
                        fields=["asset_type"], name="assets_asset_t_fc4c39_idx"
                    ),
                    models.Index(fields=["branch"], name="assets_branch_6d5ad5_idx"),
                    models.Index(
                        fields=["assigned_to"], name="assets_assigne_36a4dc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyWorkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField(db_index=True)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        help_text="Total hours worked for the day",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("sad", "Sad"),
                            ("stressed", "Stressed"),
                            ("tired", "Tired"),
                            ("frustrated", "Frustrated"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True, help_text="Challenges faced today", null=True
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Accomplishments today", null=True
                    ),
                ),
                (
                    "plan_next_day",
                    models.TextField(
                        blank=True, help_text="Plan for tomorrow", null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=1,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="Feedback", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_reports",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Work Report",
                "verbose_name_plural": "Daily Work Reports",
                "db_table": "daily_work_reports",
                "ordering": ["-day", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "day"],
                        name="daily_work__employe_4c3bd3_idx",
                    ),
                    models.Index(
                        fields=["status"], name="daily_work__status_15865d_idx"
                    ),
                ],
                "unique_together": {("employee", "day")},
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("verbal_warning", "Verbal Warning"),
                            ("written_warning", "Written Warning"),
                            ("suspension", "Suspension"),
                            ("termination", "Termination"),
                            ("final_warning", "Final Warning"),
                            ("demotion", "Demotion"),
                        ],
                        help_text="Type of disciplinary action",
                        max_length=50,
                    ),
                ),
                (
                    "violation_category",
                    models.CharField(
                        choices=[
                            ("attendance_issues", "Attendance Issues"),
                            ("misconduct", "Misconduct"),
                            ("poor_performance", "Poor Performance"),
                            ("insubordination", "Insubordination"),
                            ("dishonesty", "Dishonesty"),
                            ("safety_violation", "Safety Violation"),
                            ("confidentiality_breach", "Confidentiality Breach"),
                            ("harassment_discrimination", "Harassment/Discrimination"),
                            ("other", "Other"),
                        ],
                        help_text="Category of violation",
                        max_length=100,
                    ),
                ),
                (
                    "violation_title",
                    models.CharField(
                        help_text="Brief title of the violation", max_length=255
                    ),
                ),
                (
                    "violation_description",
                    models.TextField(help_text="Detailed description of the violation"),
                ),
                (
                    "date_of_violation",
                    models.DateField(help_text="Date when the violation occurred"),
                ),
                (
                    "action_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when the action was taken",
                    ),
                ),
                (
                    "investigation_details",
                    models.TextField(
                        blank=True,
                        help_text="Optional investigation details",
                        null=True,
                    ),
                ),
                (
                    "severance_payment_due",
                    models.BooleanField(
                        default=False, help_text="Whether severance payment is due"
                    ),
                ),
                (
                    "severance_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Severance payment amount if applicable",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_cases",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Case",
                "verbose_name_plural": "Disciplinary Cases",
                "db_table": "disciplinary_cases",
                "ordering": ["-date_of_violation", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee"], name="disciplinar_employe_6fd5be_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="disciplinar_action__08499c_idx"
                    ),
                    models.Index(
                        fields=["date_of_violation"],
                        name="disciplinar_date_of_1ba10a_idx",
                    ),
                    models.Index(
                        fields=["action_date"], name="disciplinar_action__3b802f_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="disciplinar_created_84d642_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="hr.applicant",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews_conducted",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview",
                "verbose_name_plural": "Interviews",
                "db_table": "interviews",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["applicant"], name="interviews_applica_2b43d1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="interviews_status_d52ded_idx"
                    ),
                    models.Index(
                        fields=["scheduled_at"], name="interviews_schedul_3fb753_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=models.Index(fields=["email"], name="applicants_email_323aeb_idx"),
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=models.Index(fields=["status"], name="applicants_status_c99fa2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="kpitemplatemetric",
            unique_together={("template", "metric")},
        ),
        migrations.AlterUniqueTogether(
            name="kpitemplate",
            unique_together={("department", "level")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_reque_employe_fd03a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_reque_start_d_08703b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyscorecard",
            index=models.Index(
                fields=["employee", "year", "month"],
                name="monthly_sco_employe_899af0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyscorecard",
            index=models.Index(
                fields=["-overall_score"], name="monthly_sco_overall_325bd1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyscorecard",
            unique_together={("employee", "month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="employeeevaluation",
            unique_together={("employee", "evaluator", "month", "year")},
        ),
        migrations.AddIndex(
            model_name="offerletter",
            index=models.Index(
                fields=["applicant"], name="offer_lette_applica_57aa44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerletter",
            index=models.Index(fields=["status"], name="offer_lette_status_ac2675_idx"),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["employee", "payroll_period"], name="payroll_employe_87d660_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["disbursement_date"], name="payroll_disburs_20cb89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(fields=["status"], name="payroll_status_ac0f6a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("employee", "payroll_period")},
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["employee", "review_date"],
                name="performance_employe_90c87e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["reviewer", "review_date"],
                name="performance_reviewe_0be9ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["review_period"], name="performance_review__395498_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancereview",
            unique_together={("employee", "review_period")},
        ),
    ]
