# Generated by Django 5.2.6 on 2026-03-10 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinarycase",
            name="action_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date when the action was taken",
            ),
        ),
    ]
