# Generated by Django 5.2.6 on 2026-03-11 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_disciplinarycase_action_date"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payroll",
            name="payroll_employe_87d660_idx",
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="payroll",
            name="period_date",
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payroll",
            name="disbursement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("cancelled", "Cancelled"),
                    ("paid", "Paid"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="payroll_period",
        ),
    ]
