# Generated by Django 5.2.6 on 2026-03-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_remove_payroll_payroll_employe_40ebf6_idx_and_more"),
        ("user", "0058_invoiceapproval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyworkreport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="user.employee",
            ),
        ),
    ]
