# Generated by Django 5.2.6 on 2026-03-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0059_create_role_model"),
        ("hr", "0006_alter_dailyworkreport_employee"),
        ('user', '0058_invoiceapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='user.employee'),
        ),
    ]
