# Generated by Django 5.2.6 on 2026-03-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_dailyworkreport_employee'),
        ('user', '0058_invoiceapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user.employee'),
        ),
    ]
