# Generated by Django 5.2.6 on 2026-04-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_reportattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpitemplate',
            options={'ordering': ['department']},
        ),
        migrations.AlterUniqueTogether(
            name='kpitemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='kpitemplate',
            name='level',
        ),
    ]
