# Generated by Codex on 2026-07-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_asset_imei_asset_documents_json"),
        ("hr", "0013_dailyworkreport_reviewed_at_and_more"),
    ]

    operations = []
