# Generated by Django 5.2.6 on 2026-08-17 09:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_financewalletentry_expense_and_more"),
        ("services", "0037_expense_approved_at_expense_approved_by_and_more"),
        ("user", "0096_paymentsubmission_finance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("tax_id", models.CharField(blank=True, default="", max_length=80)),
                (
                    "default_category",
                    models.CharField(
                        choices=[
                            ("materials", "Materials"),
                            ("subcontractor", "Subcontractor"),
                            ("professional_services", "Professional Services"),
                            ("technology", "Technology"),
                            ("utilities", "Utilities"),
                            ("tax_authority", "Tax Authority"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_finance_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_vendors",
                        to="user.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("category", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=255)),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "withholding_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("void", "Void"),
                        ],
                        default="awaiting_approval",
                        max_length=30,
                    ),
                ),
                ("attachment", models.URLField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills",
                        to="user.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bill_payments",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills",
                        to="services.serviceorder",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="finance.financevendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="financewalletentry",
            name="vendor_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_entries",
                to="finance.vendorbill",
            ),
        ),
        migrations.AddIndex(
            model_name="financewalletentry",
            index=models.Index(
                fields=["vendor_bill", "entry_type", "status"],
                name="finance_fin_vendor__e91040_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="financewalletentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vendor_bill__isnull", False)),
                fields=("wallet", "vendor_bill", "entry_type"),
                name="uniq_fin_wallet_vendor_bill_type",
            ),
        ),
        migrations.AddIndex(
            model_name="financevendor",
            index=models.Index(
                fields=["status", "default_category"],
                name="finance_fin_status_eb8d09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financevendor",
            index=models.Index(fields=["name"], name="finance_fin_name_1f1e4b_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["vendor", "status"], name="finance_ven_vendor__ea118a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["status", "due_date"], name="finance_ven_status_483114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["service_order", "status"],
                name="finance_ven_service_c100e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["branch", "due_date"], name="finance_ven_branch__1007cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["finance_account", "status"],
                name="finance_ven_finance_dbec5e_idx",
            ),
        ),
    ]
