# Generated by Django 5.2.6 on 2026-08-18 12:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_financebudget"),
        ("user", "0096_paymentsubmission_finance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("period_month", models.PositiveSmallIntegerField()),
                ("period_year", models.PositiveSmallIntegerField()),
                ("scheduled_payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("calculated", "Calculated"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "employee_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_payroll_runs",
                        to="user.branch",
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_finance_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_year", "-period_month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_number", models.CharField(max_length=50)),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "salary_frequency",
                    models.CharField(default="monthly", max_length=20),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("tax_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "pension_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "pfa_provider",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "rsa_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "employer_contribution_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "gross_salary_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_payroll_lines",
                        to="user.employee",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["employee_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("earning", "Earning"), ("deduction", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("base_salary", "Base Salary"),
                            ("allowance", "Allowance"),
                            ("overtime", "Overtime"),
                            ("commission", "Commission"),
                            ("bonus", "Bonus"),
                            ("reimbursement", "Reimbursement"),
                            ("other_earning", "Other Earning"),
                            ("paye", "PAYE"),
                            ("pension", "Pension"),
                            ("loan", "Loan"),
                            ("advance_recovery", "Advance Recovery"),
                            ("absence", "Absence"),
                            ("statutory", "Other Statutory Deduction"),
                            ("other_deduction", "Other Deduction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee Configuration"),
                            ("manual", "Manual Adjustment"),
                            ("commission", "Commission / Bonus"),
                            ("statutory", "Statutory Calculation"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        blank=True,
                        help_text="Tax treatment is intentionally unclassified until statutory rules are applied.",
                        null=True,
                    ),
                ),
                ("is_statutory", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_line_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.payrollline",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["payroll_line", "item_type"],
                        name="finance_pay_payroll_68abe0_idx",
                    ),
                    models.Index(
                        fields=["category", "source_type"],
                        name="finance_pay_categor_5ae11a_idx",
                    ),
                    models.Index(
                        fields=["source_reference"],
                        name="finance_pay_source__03f1db_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["period_year", "period_month"],
                name="finance_pay_period__346bd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["status", "scheduled_payment_date"],
                name="finance_pay_status_d386e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["branch", "status"], name="finance_pay_branch__7a7fae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["finance_account", "status"],
                name="finance_pay_finance_26c350_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("branch__isnull", True),
                    models.Q(("status", "cancelled"), _negated=True),
                ),
                fields=("period_year", "period_month"),
                name="uniq_active_company_payroll_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("branch__isnull", False),
                    models.Q(("status", "cancelled"), _negated=True),
                ),
                fields=("period_year", "period_month", "branch"),
                name="uniq_active_branch_payroll_period",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                fields=["payroll_run", "employee"],
                name="finance_pay_payroll_ff60cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                fields=["employee_number"], name="finance_pay_employe_7a97f1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee__isnull", False)),
                fields=("payroll_run", "employee"),
                name="uniq_fin_payroll_run_employee",
            ),
        ),
    ]
