# Generated by Django 5.2.6 on 2026-08-18 13:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_native_payroll"),
        ("services", "0038_delete_budget"),
        ("user", "0096_paymentsubmission_finance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "minimum_verified_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_commission_rules",
                        to="user.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_finance_commission_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_commission_rules",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["service__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncentiveAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[("commission", "Commission"), ("bonus", "Bonus")],
                        max_length=20,
                    ),
                ),
                (
                    "revenue_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "verified_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payout_month", models.PositiveSmallIntegerField()),
                ("payout_year", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("included_in_payroll", "Included In Payroll"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=30,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_finance_incentive_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_incentive_awards",
                        to="user.branch",
                    ),
                ),
                (
                    "commission_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="finance.commissionrule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_finance_incentive_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_incentive_awards",
                        to="user.employee",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_finance_incentive_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_incentive_awards",
                        to="services.payment",
                    ),
                ),
                (
                    "payroll_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incentive_awards",
                        to="finance.payrollline",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_finance_incentive_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_incentive_awards",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commissionrule",
            index=models.Index(
                fields=["service", "status"], name="finance_com_service_47741c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionrule",
            index=models.Index(
                fields=["branch", "status"], name="finance_com_branch__efee5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionrule",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="finance_com_effecti_b521d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaward",
            index=models.Index(
                fields=["award_type", "status"], name="finance_inc_award_t_b5a3dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaward",
            index=models.Index(
                fields=["employee", "payout_year", "payout_month"],
                name="finance_inc_employe_a78657_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaward",
            index=models.Index(
                fields=["branch", "status"], name="finance_inc_branch__7689b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaward",
            index=models.Index(
                fields=["service", "status"], name="finance_inc_service_e79d60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaward",
            index=models.Index(
                fields=["payment"], name="finance_inc_payment_8086f5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incentiveaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(("award_type", "commission")),
                fields=("payment", "employee", "commission_rule"),
                name="uniq_fin_commission_payment_employee_rule",
            ),
        ),
    ]
