# Generated by Django 5.2.6 on 2026-08-18 14:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_commissions_bonuses"),
        ("services", "0038_delete_budget"),
        ("user", "0096_paymentsubmission_finance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutoryObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obligation_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "obligation_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("wht", "Withholding Tax"),
                            ("paye", "PAYE"),
                            ("pension", "Pension"),
                            ("other", "Other Statutory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("vendor_bill", "Vendor Bills"),
                            ("payroll", "Payroll"),
                            ("invoice", "Invoice Evidence"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("period_label", models.CharField(max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("basis", models.CharField(max_length=255)),
                (
                    "basis_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_statutory_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_statutory_obligations",
                        to="user.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_statutory_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_payments",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_statutory_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_statutory_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_statutory_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatutoryObligationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("vendor_bill", "Vendor Bill"),
                            ("payroll_line_item", "Payroll Line Item"),
                            ("invoice", "Invoice Evidence"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_reference", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=255)),
                (
                    "basis_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "liability_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_items",
                        to="services.invoice",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.statutoryobligation",
                    ),
                ),
                (
                    "payroll_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_items",
                        to="finance.payrolllineitem",
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_items",
                        to="finance.vendorbill",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="statutoryobligation",
            index=models.Index(
                fields=["obligation_type", "status"],
                name="finance_sta_obligat_7b89ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligation",
            index=models.Index(
                fields=["due_date", "status"], name="finance_sta_due_dat_3e8013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligation",
            index=models.Index(
                fields=["branch", "status"], name="finance_sta_branch__92ac35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligation",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="finance_sta_period__578a93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligationitem",
            index=models.Index(
                fields=["source_type", "source_reference"],
                name="finance_sta_source__6c0903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligationitem",
            index=models.Index(
                fields=["vendor_bill"], name="finance_sta_vendor__9f47ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligationitem",
            index=models.Index(
                fields=["payroll_line_item"], name="finance_sta_payroll_26e7e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryobligationitem",
            index=models.Index(
                fields=["invoice"], name="finance_sta_invoice_d31b0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statutoryobligationitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vendor_bill__isnull", False)),
                fields=("vendor_bill",),
                name="uniq_statutory_vendor_bill_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="statutoryobligationitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payroll_line_item__isnull", False)),
                fields=("payroll_line_item",),
                name="uniq_statutory_payroll_item_source",
            ),
        ),
    ]
