# Generated by Django 5.2.6 on 2026-08-19 13:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_bank_cash_account_controls"),
        ("user", "0096_paymentsubmission_finance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journal_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("entry_date", models.DateField()),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                            ("reversal", "Reversal"),
                            ("opening", "Opening Balance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("posted", "Posted")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("memo", models.TextField(blank=True, default="")),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=80)),
                (
                    "source_event",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="user.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_entry",
                        to="finance.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("is_postable", models.BooleanField(default=True)),
                (
                    "system_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accounts_receivable", "Accounts Receivable"),
                            ("accounts_payable", "Accounts Payable"),
                            ("employee_receivables", "Employee Receivables"),
                            ("service_revenue", "Service Revenue"),
                            ("service_cost_expense", "Service Cost Expense"),
                            ("operating_expense", "Operating Expense"),
                            (
                                "capital_expenditure_clearing",
                                "Capital Expenditure Clearing",
                            ),
                            ("payroll_expense", "Payroll Expense"),
                            (
                                "payroll_deductions_payable",
                                "Payroll Deductions Payable",
                            ),
                            ("statutory_payable", "Statutory Payable"),
                            ("petty_cash_advance", "Petty Cash Advance"),
                            ("opening_balance_equity", "Opening Balance Equity"),
                        ],
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ledger_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.ledgeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_order", models.PositiveIntegerField(default=1)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="finance.ledgeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["journal_entry_id", "line_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="financeaccount",
            name="ledger_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_account",
                to="finance.ledgeraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["status", "entry_date"], name="finance_jou_status_8dc373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["currency", "entry_date"], name="finance_jou_currenc_6a3466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["branch", "entry_date"], name="finance_jou_branch__9fb3ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_type", "source_id", "source_event"],
                name="finance_jou_source__abb00b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", ""), _negated=True),
                fields=("source_type", "source_id", "source_event"),
                name="uniq_fin_journal_source_event",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["account_type", "is_active"],
                name="finance_led_account_800a76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["parent", "is_active"], name="finance_led_parent__2e118c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["is_postable", "is_active"],
                name="finance_led_is_post_45ee70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["ledger_account", "journal_entry"],
                name="finance_jou_ledger__3f0b39_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.UniqueConstraint(
                fields=("journal_entry", "line_order"),
                name="uniq_fin_journal_line_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit", 0), ("debit__gt", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="fin_journal_line_one_side_positive",
            ),
        ),
    ]
