# Generated by Django 5.2.6 on 2026-08-19 15:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_seed_chart_of_accounts"),
            ("user", "0096_paymentsubmission_finance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgeraccount",
            name="system_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accounts_receivable", "Accounts Receivable"),
                    ("accounts_payable", "Accounts Payable"),
                    ("employee_receivables", "Employee Receivables"),
                    ("service_revenue", "Service Revenue"),
                    ("service_cost_expense", "Service Cost Expense"),
                    ("operating_expense", "Operating Expense"),
                    ("capital_expenditure_clearing", "Capital Expenditure Clearing"),
                    ("payroll_expense", "Payroll Expense"),
                    ("payroll_deductions_payable", "Payroll Deductions Payable"),
                    ("statutory_payable", "Statutory Payable"),
                    ("petty_cash_advance", "Petty Cash Advance"),
                    ("opening_balance_equity", "Opening Balance Equity"),
                    ("asset_disposal_gain", "Asset Disposal Gain"),
                    ("asset_disposal_loss", "Asset Disposal Loss"),
                ],
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_start_date", models.DateField()),
                ("statement_end_date", models.DateField()),
                (
                    "statement_opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "statement_closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reconciled", "Reconciled"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_reconciliations",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_end_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=160)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("debit", "Debit / money out"),
                            ("credit", "Credit / money in"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_lines",
                        to="finance.bankreconciliation",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_reconciliation_id", "sequence_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("matched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bank_reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="finance.bankreconciliation",
                    ),
                ),
                (
                    "journal_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_reconciliation_matches",
                        to="finance.journalline",
                    ),
                ),
                (
                    "matched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_reconciliation_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank_statement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="finance.bankstatementline",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_reconciliation_id", "bank_statement_line_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="FixedAssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("default_useful_life_months", models.PositiveIntegerField()),
                (
                    "default_residual_value_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "default_depreciation_method",
                    models.CharField(
                        choices=[("straight_line", "Straight line")],
                        default="straight_line",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accumulated_depreciation_ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_accumulated_depreciation_categories",
                        to="finance.ledgeraccount",
                    ),
                ),
                (
                    "asset_ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_cost_categories",
                        to="finance.ledgeraccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fixed_asset_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depreciation_expense_ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_depreciation_expense_categories",
                        to="finance.ledgeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("acquisition_date", models.DateField()),
                ("capitalization_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "residual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("useful_life_months", models.PositiveIntegerField()),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("straight_line", "Straight line")],
                        default="straight_line",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("fully_depreciated", "Fully depreciated"),
                            ("disposed", "Disposed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("disposed_at", models.DateField(blank=True, null=True)),
                (
                    "disposal_proceeds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "disposal_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("disposal_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accumulated_depreciation_ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_accumulated_depreciation",
                        to="finance.ledgeraccount",
                    ),
                ),
                (
                    "asset_ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_at_cost",
                        to="finance.ledgeraccount",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_assets",
                        to="user.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fixed_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depreciation_expense_ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_depreciation_expense",
                        to="finance.ledgeraccount",
                    ),
                ),
                (
                    "disposal_finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_disposals",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "source_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="services.expense",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="finance.fixedassetcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_number"],
            },
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["finance_account", "statement_end_date"],
                name="finance_ban_finance_53e561_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["status", "statement_end_date"],
                name="finance_ban_status_52f27c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["bank_reconciliation", "transaction_date"],
                name="finance_ban_bank_re_fcf31a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["reference"], name="finance_ban_referen_7f49fc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.UniqueConstraint(
                fields=("bank_reconciliation", "sequence_number"),
                name="uniq_fin_bank_statement_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_transaction_id", ""), _negated=True),
                fields=("bank_reconciliation", "external_transaction_id"),
                name="uniq_fin_bank_statement_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliationmatch",
            index=models.Index(
                fields=["bank_reconciliation", "journal_line"],
                name="finance_ban_bank_re_600980_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliationmatch",
            index=models.Index(
                fields=["bank_statement_line", "journal_line"],
                name="finance_ban_bank_st_c0ed7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankreconciliationmatch",
            constraint=models.UniqueConstraint(
                fields=("bank_statement_line", "journal_line"),
                name="uniq_fin_bank_statement_journal_match",
            ),
        ),
        migrations.AddIndex(
            model_name="fixedassetcategory",
            index=models.Index(
                fields=["is_active", "name"], name="finance_fix_is_acti_c5639e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["status", "branch"], name="finance_fix_status_24bb87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["category", "status"], name="finance_fix_categor_8fa77e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["source_expense"], name="finance_fix_source__0f3825_idx"
            ),
        ),
    ]
