"""
Django settings for bomach_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

DOMAIN = config("DOMAIN", default="bomach-os-app.web.app")

sentry_sdk.init(
    dsn=config("GLITCHTIP_DSN"),
    integrations=[DjangoIntegration()],
    auto_session_tracking=False,
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for tracing.
    traces_sample_rate=0.01,
    release="1.0.0",
    environment="production",
)

# ALLOWED_HOSTS configuration
# In production, set ALLOWED_HOSTS environment variable with your domains
# Format: domain1.com,domain2.com,.onrender.com

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    "192.168.0.214",
    "192.168.0.188",
    ".ngrok-free.app",
    ".onrender.com",
    "bomachauthtest.bgbot.app",
    "services-mocha-xi.vercel.app",
]
_ALLOWED_HOSTS = config("ALLOWED_HOSTS", "")
ALLOWED_HOSTS.extend(_ALLOWED_HOSTS.split())

ZOHOZEPTOMAIL_KEY = config("ZOHOZEPTOMAIL_KEY", default="")

FRONTEND_PRODUCTION_DOMAIN = config("FRONTEND_PRODUCTION_DOMAIN", default="")

FACE_SERVICE_URL = config(
    "FACE_SERVICE_URL",
    default="",
).rstrip("/")
FACE_SERVICE_API_KEY = config(
    "FACE_SERVICE_API_KEY",
    default="",
)
FACE_SERVICE_CONNECT_TIMEOUT = config(
    "FACE_SERVICE_CONNECT_TIMEOUT",
    default=2.0,
    cast=float,
)
FACE_SERVICE_RESPONSE_TIMEOUT = config(
    "FACE_SERVICE_RESPONSE_TIMEOUT",
    default=30.0,
    cast=float,
)
FACE_EMBEDDING_DIMENSION = config(
    "FACE_EMBEDDING_DIMENSION",
    default=512,
    cast=int,
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_extensions",
    "user",
    "hr",
    "operations",
    "services",
    "finance",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise for static files
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "user.utils.middleware.ResponseFormaterMiddleware",
]

ROOT_URLCONF = "bomach_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "template"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bomach_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration controlled by TRY_LOCAL_DB flag
TRY_LOCAL_DB = config("TRY_LOCAL_DB", default=False, cast=bool)

if TRY_LOCAL_DB:
    # Use SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Use PostgreSQL from environment variables
    DATABASES = {
        "default": {
            "ENGINE": config(
                "DATABASES_DEFAULT_ENGINE", default="django.db.backends.postgresql"
            ),
            "NAME": config("DATABASES_DEFAULT_NAME"),
            "USER": config("DATABASES_DEFAULT_USER"),
            "PASSWORD": config("DATABASES_DEFAULT_PASSWORD"),
            "HOST": config("DATABASES_DEFAULT_HOST"),
            "PORT": config("DATABASES_DEFAULT_PORT", default="5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="").strip()
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="").strip()
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="").strip()
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="").strip()
AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default="").strip()

USE_S3_MEDIA_STORAGE = bool(AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME)

STORAGES = {
    "default": (
        {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "region_name": AWS_S3_REGION_NAME,
                "file_overwrite": False,
                "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            },
        }
        if USE_S3_MEDIA_STORAGE
        else {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": BASE_DIR / "mediafiles",
                "base_url": "/media/",
            },
        }
    ),
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise configuration for serving static files in production
# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "user.User"

# Email Configuration
EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"  # Development: prints to console
)
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = "noreply@benji.com"

# Monnify Payment Gateway
MONNIFY_API_KEY = config("MONNIFY_API_KEY", default="")
MONNIFY_SECRET_KEY = config("MONNIFY_SECRET_KEY", default="")
MONNIFY_BASE_URL = config("MONNIFY_BASE_URL", default="https://api.monnify.com")


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "bomach-cache",
    }
}

FLUTTER_LOCAL_ORIGINS = ["http://127.0.0.1:52240", "https://bomach-os-client.web.app"]

CORS_ALLOWED_ORIGIN_REGEXES = (
    [
        r"^http://localhost:\d+$",
        r"^https://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
        r"^https://127\.0\.0\.1:\d+$",
    ]
    if DEBUG
    else []
)
CORS_ALLOWED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = []

# Add Flutter production domains
for domain in FRONTEND_PRODUCTION_DOMAIN.split():
    CSRF_TRUSTED_ORIGINS.append(f"https://{domain}")
    CORS_ALLOWED_ORIGINS.append(f"https://{domain}")

# Add Flutter local development origins
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(FLUTTER_LOCAL_ORIGINS)
    CSRF_TRUSTED_ORIGINS.extend(FLUTTER_LOCAL_ORIGINS)

# Add backend allowed hosts
for host in _ALLOWED_HOSTS.split():
    CSRF_TRUSTED_ORIGINS.append(f"http://{host}")
    CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
    CORS_ALLOWED_ORIGINS.append(f"http://{host}")
    CORS_ALLOWED_ORIGINS.append(f"https://{host}")

CORS_ALLOWED_ORIGINS.append("https://bomach-os-test.web.app")
CORS_ALLOWED_ORIGINS.append("http://bomach-os-test.web.app")
CORS_ALLOWED_ORIGINS.append("https://services-mocha-xi.vercel.app")
CORS_ALLOWED_ORIGINS.append("http://services-mocha-xi.vercel.app")
CORS_ALLOWED_ORIGINS.append("https://marketing-wine-alpha.vercel.app")
CORS_ALLOWED_ORIGINS.append("http://marketing-wine-alpha.vercel.app")
CSRF_TRUSTED_ORIGINS.append("https://bomach-os-test.web.app")
CSRF_TRUSTED_ORIGINS.append("http://bomach-os-test.web.app")


# Additional CORS headers for Flutter web
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_CREDENTIALS = True

CORS_EXPOSE_HEADERS = [
    "content-type",
    "x-csrf-token",
]

# The initial "Bank" for the company
COMPANY_WALLET_BALANCE = 10000000.00

# Security Settings (Production)
# These settings are environment-aware and only apply when appropriate
# if not DEBUG:
#     # HTTPS/SSL Settings
#     SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
#     SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
#     CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)

#     # HSTS Settings
#     SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 year
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
#     SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)

#     # Other security settings
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     SECURE_BROWSER_XSS_FILTER = True
#     X_FRAME_OPTIONS = 'DENY'
