from .test_employee_utils import ResolveReportingToEmployeeTests
from .test_role_authority_limits import RoleAuthorityLimitsAPITests
from .test_role_career_path import RoleCareerPathAPITests
from .test_role_descriptions import RoleDescriptionAPITests
from .test_role_kpis import EmployeeKPIRecordAPITests, RoleKPIMetricAPITests
from .test_role_resources import RoleResourceAPITests
from .test_role_success_playbook import RoleSuccessPlaybookAPITests
from .test_role_targets import EmployeeTargetAPITests, RoleTargetTemplateAPITests
from .test_target_reports import TargetReportAPITests
from .test_role_training_and_sops import (
    RoleSOPAPITests,
    RoleTrainingRequirementAPITests,
)
from .test_role_workflows import RoleDailyRoutineAPITests, RoleTaskTemplateAPITests
